permission: refactoring the loan permission factory
rero/rero-ils pull request #1170
Opened 2020-08-19 15:01 UTC by zannkukai

This commit creates specific permission class relative to invenio
circulation resource. This commit also simplify some "seacrh_factory"
methods and correct the loan "search_factory" method (error if an user
has the roe `patron` and `librarian`)

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-08-20 04:28 UTC, iGormilhit requested changes
Commit typos: there a `seacrh_factory` instead of a `search_factory`, and a `roe` instead of a `role`. Otherwise this commit message is fine.

2020-08-20 05:52 UTC, BadrAly approved these changes
assuming that you are fixing the travis testing problems

2020-08-20 14:32 UTC, benerken approved these changes

2020-08-21 04:34 UTC, lauren-d approved these changes

2020-08-24 04:59 UTC, iGormilhit approved these changes
Commit message approved.

2020-08-24 13:14 UTC, merged