document: draft records are excluded from search results
rero/rero-ils pull request #1173
Opened 2020-08-20 09:21 UTC by BadrAly

Co-Authored-by: Aly Badr <aly.badr@rero.ch>

## Why are you opening this PR?

https://tree.taiga.io/project/rero21-reroils/task/1662?kanban-status=1224894

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-08-20 12:05 UTC, lauren-d approved these changes

2020-08-21 06:54 UTC, rerowep approved these changes

2020-08-24 04:46 UTC, iGormilhit requested changes
The commit message title is too long (longer than 50 chars). My proposition: "document: exclude drafts from search results".

Then, in the commit message body, a small explanation could be useful, mentionning the rero/rero-ils#1155 PR that introduced the draft records, and adding a small sentence on why we don't want these drafted record to be searched.

2020-08-25 04:42 UTC, iGormilhit approved these changes
Commit message approved.

2020-08-25 10:01 UTC, merged