circulation: fix validate request return type
rero/rero-ils pull request #1177
Opened 2020-08-24 13:03 UTC by zannkukai

When a request is cancel, if another should be validated, the return
statement was wrong (double dict key). This commit fixes this problem
and return a correct actions applied list.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-08-24 14:00 UTC, BadrAly approved these changes

2020-08-25 04:51 UTC, iGormilhit requested changes
Commit message changes (bold):

When a request is cancel**ed**, if another **one has to** be validated,
the return statement **is** wrong (double dict key). This commit fixes
this problem and return**s** a correct actions applied list.

2020-08-25 06:49 UTC, iGormilhit approved these changes

2020-08-25 07:11 UTC, AoNoOokami approved these changes

2020-08-25 12:21 UTC, merged