acquisition: add document typeahead in order lines editor
rero/rero-ils pull request #1185
Opened 2020-08-28 12:55 UTC by lauren-d

* Adapts order lines JSON schema.

Co-Authored-by: Lauren-D <laurent.dubois@itld-solutions.be>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#350

## How to test?

- Test document typeahead in order lines editor.

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-08-28 14:05 UTC, zannkukai approved these changes

2020-08-29 10:24 UTC, benerken approved these changes

2020-08-31 04:42 UTC, iGormilhit requested changes
Commit message proposition, adapt it as you think is appropriate. First, the commit title should be max 50 chars long, and a small explanation is needed:

```
acquisition: add document selector for order lines

Adds a search input in the order line editor to link an order line to a
document, preventing the user to enter a valid API URL.

* Adapts order lines JSON schema.
```

2020-08-31 08:32 UTC, iGormilhit approved these changes

2020-08-31 09:58 UTC, AoNoOokami approved these changes

2020-08-31 13:06 UTC, BadrAly approved these changes

2020-09-01 09:49 UTC, jma approved these changes

2020-09-03 11:30 UTC, merged