patrons: fix patron CLI creation problem.
rero/rero-ils pull request #1250
Opened 2020-09-30 11:52 UTC by zannkukai

Using the CLI `import_users` keeps some pids into the `patron_pid` db
table. This will cause problem to create new user after the setup (using
API or UI. This commit cleans the user creation.
This commit also update template resource facet configuration and ES
mapping (to allow resource name sorting).

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## How to test?

- run `bootstrap` & `setup`
- start the UI (localhost:4200) and create a  new user (role doesn't matter).

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-10-01 10:38 UTC, lauren-d commented
I think that the final dot can be removed from commit message title.

2020-10-05 07:29 UTC, AoNoOokami approved these changes

2020-10-05 08:08 UTC, lauren-d approved these changes

2020-10-12 07:52 UTC, rerowep requested changes

2020-10-12 07:52 UTC, rerowep commented on scripts/setup
> +eval ${PREFIX} invenio fixtures import_users ${DATA_PATH}/users.json -v --append
We have no test if a user exist already any more if we index all users at the end. See `get_pid_by_email`!

2020-10-12 11:48 UTC, rerowep approved these changes

2020-10-12 12:35 UTC, merged