select widget: change select with selectWithSort
rero/rero-ils pull request #1276
Opened 2020-10-12 13:24 UTC by Garfield-fr

* Changes select to selectWithSort on document contribution role.
* Close issue#1231

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/ng-core#281

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-10-13 06:17 UTC, BadrAly approved these changes

2020-10-13 07:40 UTC, zannkukai approved these changes

2020-11-01 09:23 UTC, rerowep approved these changes

2020-11-04 06:47 UTC, iGormilhit requested changes
Commit message proposition:
```
cument: sort contribution roles

* Changes the document JSON schema form options from select to
  selectWithSort on the contribution roles in order to sort them
  alphabetically in the editor.
* Closes #1231
```

2020-11-04 11:35 UTC, iGormilhit approved these changes

2020-11-04 11:47 UTC, merged