ill_request: fix form validation problem
rero/rero-ils pull request #1315
Opened 2020-10-19 13:33 UTC by zannkukai

When user submit the ill request form with some values, either the
server return an error either bad data are saved into the request :
  * no date selected --> 'None' string was saved.
  * found_in.source specified and no url --> server error
  * invalid URL in found_in.url --> server error

This commit also fixes some bugs due t item call_number that is now not
required. Introducing a new Jinja filter to display an custom message if
no data is available.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-10-20 05:01 UTC, Garfield-fr approved these changes

2020-10-20 06:49 UTC, lauren-d approved these changes

2020-10-21 08:44 UTC, iGormilhit requested changes
Commit message proposition:
```
ill_request: fix form validation issues 

When the user submit the ill request form, either the server return an
error, or bad data are saved:
  * no date selected → 'None' string was saved.
  * found_in.source specified and no url → server error
  * invalid URL in found_in.url → server error

This pull request also fixes some bugs due to the item call_number that
is not required anymore. It introduces also a new Jinja filter to
display an custom message if no data is available.
```

2020-10-21 09:25 UTC, iGormilhit approved these changes
Commit message approved.

2020-10-27 07:49 UTC, merged