patron_type: update JSON schema for borrow limits
rero/rero-ils pull request #1324
Opened 2020-10-21 12:36 UTC by zannkukai

* Adapts the patron_type JSON schema to include a section about borrow
limits.
* Adds some unit tests to validate the schema constraints

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-10-21 13:46 UTC, lauren-d approved these changes

2020-10-22 06:18 UTC, benerken approved these changes

2020-10-22 06:50 UTC, iGormilhit requested changes
Commit message proposition (maybe it's wrong and you can do better...):
```
patron_type: implements checkouts restrictions 

* Adapts the patron_type JSON schema to include a section about checkout
  restrictions. There are three type of restrictions: number of checkouts, fee
  amount, and  number of overdue items.
* Adds some unit tests to validate the schema constraints.
```

2020-10-22 06:50 UTC, iGormilhit commented on rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
> +              "description": "The checkout is blocked once the specified checkout number is reached by the patron for items of a same owning library. This is the same limit for all libraries.",
```suggestion
              "description": "The checkout is blocked once the specified checkout number is reached by the patron for items of the same owning library. This is the same limit for all libraries.",
```

2020-10-22 07:42 UTC, zannkukai commented on rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
> +              "description": "The checkout is blocked once the specified checkout number is reached by the patron for items of a same owning library. This is the same limit for all libraries.",
done

2020-10-26 06:39 UTC, iGormilhit approved these changes
Commit message approved.

2020-10-26 12:13 UTC, BadrAly requested changes

2020-10-26 12:13 UTC, BadrAly commented on rero_ils/modules/patron_types/jsonschemas/patron_types/patron_type-v0.0.1.json
> +            "general_limit",
`global_limit` or `organisational_limit` I think better than `general_limit` ?

2020-10-26 17:22 UTC, BadrAly approved these changes

2020-10-27 07:24 UTC, merged