circulation: hide buttons if action isn't available.
rero/rero-ils pull request #1354
Opened 2020-11-02 13:35 UTC by zannkukai

If the patron can't operate an action due to circulation restrictions
(patron blocked, patron type limits, ...), circulation buttons should be
hide. In the patron profile view, adds warning/error messages depending
of patron restrictions.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## How to test?

![image](https://user-images.githubusercontent.com/10031585/97873925-9029a100-1d18-11eb-8568-e1c82b4e9249.png)

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-11-03 12:20 UTC, Garfield-fr approved these changes

2020-11-03 15:49 UTC, lauren-d requested changes

2020-11-03 15:49 UTC, lauren-d commented on rero_ils/modules/patrons/templates/rero_ils/_patron_profile_requests.html
> +          {{ _('to pick uup') }}
change `to pick uup` to `to pick up` 🙃?

2020-11-03 17:12 UTC, ManaDeweerdt commented
When I try to checkout an item I get an error 'item not found'.
But I can checkin and checkout an item already borrowed.

2020-11-03 18:20 UTC, ManaDeweerdt commented
Like the https://github.com/rero/rero-ils/issues/1357 the button 'request' should be visible even he has the limits reached, followed by an explanation.

2020-11-03 20:48 UTC, benerken commented
Great job Renaud ! 
some comments for now:

- If we define a general checkout limit only => the system displays a message when you arrive on the patron account in the professional view  AND  It displays a flash message when you do a checkout  => OK
(A permanent message is displayed in the patron public view) => OK

- If we define a general checkout limit AND a library checkout limit => the system doesn't display a permanent message when you arrive on the patron account in the professional view. It displays a flash message when you do a checkout. Why ? 
(Same behaviour in the patron public view => No permanent message)

2020-11-04 06:40 UTC, iGormilhit requested changes
Commit message body: replace twice *disable* by *disabled*. Thanks.

2020-11-04 08:00 UTC, zannkukai commented
> Like the #1357 the button 'request' should be visible even he has the limits reached, followed by an explanation. [enhancement]

It's more difficult :: One of the main reason why an item is not requestable is because the item is not in the same organisation than patron. In this case, it's not user friendly to get the button disabled with this message.

2020-11-04 09:21 UTC, lauren-d approved these changes

2020-11-04 11:42 UTC, pronguen commented
* Wording
  * The unit of the field for each limit should be clearer in the field label (same problem than in cipo, https://github.com/rero/rero-ils/issues/1305).
  * I don't understand the word *default* in some of the labels.
  * The label should correspond to the description given below and does not need to repeat the info given in the toggle.
  * Suggestions:
    * Global checkout limit > Number of checkouts in the organisation
    * Default checkout limit by library > Number of checkouts by library
    * Default fee amount limit > Fee amount
    * Default overdue items limit > Number of overdue items
![image](https://user-images.githubusercontent.com/8154915/98103193-efacbb80-1e94-11eb-8d55-469632c549c1.png)
* Message in public interface (for patrons)
  * Don't display any message above, in the patron account (simplification), as they are note user-friendlyI think it is enough to display the message on the disabled buttons as tooltip.
    * Potential problem: the user does not know that he cannot request document. But if we display the request button in any case (sometimes disabled) it will solve this. See also Mana's comment [can be done later, issue can be opened].
  * Tooltips on buttons (request/renew): adapt if possible to end user, as specified in the US: "Renewal impossible: you have too many overdue items." / "Renewal impossible: you have too many fees." / etc.
  * Tootips in Google Chrome (Version 86.0.4240.183 (Build officiel) (64 bits)) is problematic: no tooltip for the first item to renew, other tooltip permanent (see screenshot)
  * This works on Firefox
![image](https://user-images.githubusercontent.com/8154915/98104911-68ad1280-1e97-11eb-87c6-49b801855729.png)
* Circulation interface
  * Simplification of the flash message: the first part could be used as first line. In example below, use "Checkout denied" as first line.
![image](https://user-images.githubusercontent.com/8154915/98105327-19b3ad00-1e98-11eb-8cb2-129bfb53cc06.png)
  * [enhancement] Ideally, the messages display above in user checkout account are adapted. Now they are answer messages after an action tried.
* General
  * Limit by fee amount includes only overdue fees? Or it just does not include subscription fees? To decide, we may need to adapt the labels and messages.

2020-11-05 15:38 UTC, merged