deployment: fix poetry
rero/rero-ils pull request #1412
Opened 2020-11-06 12:22 UTC by rerowep

* fixes version of poetry < 1..0.

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-11-06 14:25 UTC, BadrAly approved these changes

2020-11-09 07:14 UTC, iGormilhit requested changes
Commit message proposition:

```
deployment: fix poetry version to < 1.1.0

Co-Authored-by: Peter Weber <peter.weber@rero.ch>
```
No message body needed here.

2020-11-09 07:47 UTC, iGormilhit approved these changes

2020-11-11 08:01 UTC, jma approved these changes

2020-11-12 10:04 UTC, iGormilhit commented
Already integrated to the dev branch.

2020-11-12 10:04 UTC, closed without merging