github: fix github actions
rero/rero-ils pull request #1446
Opened 2020-11-17 09:19 UTC by rerowep

* Fixes poetry install in github actions.

Unable to process command '##[add-path]/home/runner/.poetry/bin' successfully.
The `add-path` command is disabled. Please upgrade to using Environment Files or
opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS`
environment variable to `true`. For more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-11-17 09:20 UTC, lauren-d approved these changes

2020-11-17 09:21 UTC, AoNoOokami approved these changes

2020-11-17 09:25 UTC, AoNoOokami commented
Are we sure we want to allow unsecure commands?

2020-11-17 10:15 UTC, rerowep commented
> Are we sure we want to allow unsecure commands? I think we should add a TODO in order not to forgot to fix that properly later.

If this issue is solved we can change back: https://github.com/dschep/install-poetry-action/issues/19

2020-11-17 13:26 UTC, rerowep commented
I found a better Github Action without the problem:
https://github.com/snok/install-poetry

2020-11-18 06:37 UTC, iGormilhit requested changes
For the commit message title: `CI: fix github actions` is better.

But I can't understand a thing of the message body ! :slightly_smiling_face:

2020-11-18 09:03 UTC, BadrAly approved these changes

2020-11-18 09:07 UTC, zannkukai approved these changes

2020-11-18 10:05 UTC, iGormilhit approved these changes
Commit message approved.

2020-11-18 10:09 UTC, merged