cypress: fix tests after v0.14
rero/rero-ils pull request #1448
Opened 2020-11-17 15:36 UTC by AoNoOokami

* Adapts circulation scenarios tests according to new html template.
* Adds an alias to wait for schemaform loading before the population of the document editor.

Co-Authored-by: Alicia Zangger <alicia.zangger@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-11-18 06:31 UTC, iGormilhit requested changes
Commit message minor corrections:

```
tests: fix Cypress tests after v0.14.0

* Adapts circulation scenarios tests according to new HTML template.
* Adds an alias to wait for schemaform loading before the population of
  the document editor.
```

2020-11-22 06:10 UTC, benerken approved these changes

2020-11-24 14:04 UTC, iGormilhit approved these changes

2020-11-25 16:34 UTC, zannkukai approved these changes

2020-11-26 15:38 UTC, merged