notes: allow notes of short size
rero/rero-ils pull request #1476
Opened 2020-11-20 09:38 UTC by BadrAly

Holdings, patron and items notes are now
have a minimum length of 1 character instead
of 3 characters. This to allow libraries to
use notes as codes for some internal uses cases.

Co-Authored-by: Aly Badr <aly.badr@rero.ch>

## Why are you opening this PR?

https://tree.taiga.io/project/rero21-reroils/task/1880?kanban-status=1224895

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

You can not add holdings/patron/item notes  of size `1`

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-11-20 15:42 UTC, benerken approved these changes

2020-11-20 17:32 UTC, zannkukai approved these changes

2020-11-23 06:02 UTC, iGormilhit requested changes
Commit message body:

```
Sets the note minimum length of holdings, patron and item to 1 instead
of 3 characters, to allow libraries to use notes as codes for some
internal uses cases.
```

2020-11-23 08:53 UTC, iGormilhit approved these changes
Commit message approved.

2020-11-23 09:28 UTC, merged