patron: minimum length size for some patron fields
rero/rero-ils pull request #1479
Opened 2020-11-20 12:14 UTC by BadrAly

The following fields can now have a minimum length
of 1 character:

    * patron.city
    * patron.postal_code
    * patron.street
    * item.barcode

Co-Authored-by: Aly Badr <aly.badr@rero.ch>

## Why are you opening this PR?

https://tree.taiga.io/project/rero21-reroils/task/1884?kanban-status=1224895

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-11-20 15:42 UTC, benerken approved these changes

2020-11-23 06:13 UTC, iGormilhit requested changes
Commit message proposition:

```
data: set several minLength to 1 

Sets the minimum length of the following fields to 1 character:

* patron.city
* patron.postal_code
* patron.street
* item.barcode

Co-Authored-by: Aly Badr <aly.badr@rero.ch>
```

And a small explanation on why it's needed would be fine. Is it to reflect the actual data?

2020-11-23 06:55 UTC, pronguen approved these changes

2020-11-23 07:11 UTC, jma reviewed
The commit message seems too generic. I would merge this PR with: https://github.com/rero/rero-ils/pull/1476

2020-11-23 07:45 UTC, iGormilhit approved these changes

2020-11-23 09:29 UTC, merged