loan: hide loans according to user request
rero/rero-ils pull request #1483
Opened 2020-11-20 16:36 UTC by BadrAly

Co-Authored-by: Aly Badr <aly.badr@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-11-24 12:32 UTC, zannkukai requested changes

2020-11-24 12:32 UTC, zannkukai commented on rero_ils/modules/loans/api.py
> +        return False
```
         return (
            self.get('state') in states and
            not loan_has_open_events(loan_pid=self.pid)
        )
```

2020-11-24 12:32 UTC, zannkukai commented on rero_ils/modules/loans/api.py
> +        return False
`return not keep_history and self.concluded`

2020-11-24 12:32 UTC, zannkukai commented on rero_ils/modules/loans/api.py
> +        'term', loan__pid=loan_pid).source().scan()
add 'pid' into `.source` to return only pid value ==> lighter ES call :: `.source(['pid']).scan()`

2020-11-24 12:32 UTC, zannkukai commented on rero_ils/modules/loans/api.py
> +                return True
```
for record in search:
  transactions_count = PatronTransactionsSearch()
      .filter('term', notification__pid=record.pid)
      .filter('term', status='open')
      .source().count()
  if transction_count:
      return True
```
Using this method, you avoid to loop all values from the first loop + an useless `if` statement

2020-11-24 15:13 UTC, zannkukai approved these changes

2020-11-25 06:56 UTC, iGormilhit requested changes
Commit message proposition:

```
users: set whether to keep loan history or not

A new boolean `keep_history` field is added to patron record to either
maintain circulation transaction history for the last 6 months or to
anonymize the transaction once it is concluded.

A loan is considered concluded if it is in the ITEM_RETURNED or
CANCELLED state and has no open patron transactions (fees).

A new field added to the loan record `to_anonymize` to set the record to
be anonymized.
```

2020-11-25 06:56 UTC, iGormilhit commented on rero_ils/modules/loans/jsonschemas/loans/loan-ils-v0.0.1.json
> +    },
```suggestion
    "to_anonymize": {
      "title": "Set loan to be anonymized",
      "description": "If enabled, loan will be anonymized. currently it is not returned for loan searches.",
      "type": "boolean",
      "default": false
    },
```
Actually, the description is a little bit misleading. "... set to be anonymized" is more accurate.

2020-11-25 06:56 UTC, iGormilhit commented on rero_ils/modules/loans/api.py
> +        """
```suggestion
    def can_anonymize(self):
        """Check if a loan can be anonymized  and excluded from loan searches.

        Loan can be anonymized if its patron has the keep_history set to False
        and the loan is concluded.

        :return True|False.
        """
```

2020-11-25 06:56 UTC, iGormilhit commented on rero_ils/modules/loans/mappings/v7/loans/loan-ils-v0.0.1.json
> +      "to_anonymise": {
```suggestion
      "to_anonymize": {
```

2020-11-25 06:56 UTC, iGormilhit commented on rero_ils/modules/patrons/jsonschemas/patrons/patron-v0.0.1.json
> +          "description": "If the keep_history is enabled, it will keep the loans of the 6 last months.",
```suggestion
          "description": "When enabled, track of the loan history of the 6 last months will be kept.",
```

2020-11-25 06:56 UTC, iGormilhit commented on tests/ui/loans/test_loans_api.py
> +    assert not loan.can_anonymise()
```suggestion
    assert not loan.can_anonymize()
```

2020-11-25 06:56 UTC, iGormilhit commented on tests/ui/loans/test_loans_api.py
> +
```suggestion
    # when the patron asks to anonymize history the can_anonymize is true
    assert loan.concluded
    assert loan.can_anonymize()

```

2020-11-25 06:56 UTC, iGormilhit commented on tests/ui/loans/test_loans_api.py
> +    assert not loan.can_anonymise()
```suggestion
    assert not loan.can_anonymize()
```

2020-11-25 06:56 UTC, iGormilhit commented on tests/ui/loans/test_loans_api.py
> +    assert not loan.can_anonymise()
```suggestion
    assert not loan.can_anonymize()
```

2020-11-25 07:21 UTC, AoNoOokami approved these changes

2020-11-25 08:25 UTC, iGormilhit approved these changes

2020-11-25 09:10 UTC, lauren-d approved these changes

2020-11-25 11:45 UTC, merged