circulation: add control on circulation operation.
rero/rero-ils pull request #1502
Opened 2020-11-25 13:10 UTC by zannkukai

Closes rero/rero-ils#1470
If a circulation policy disallow checkout operation, the error message
returned was not user friendly. This commit add a check for checkout
operation on cipo; this check return a better error message.

Closes rero/rero-ils#1383
If a patron is blocked for any reasons, this user couldn't extend any
active loan.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2020-11-26 05:14 UTC, Garfield-fr approved these changes

2020-11-26 06:16 UTC, iGormilhit requested changes
Minor commit changes:

```
circulation: add control on circulation operation

Closes rero/rero-ils#1470
If a circulation policy disallow checkout operation, the error message
returned was not user friendly. This commit add a check for checkout
operation on circulation policy; this check return a better error
message.

Closes rero/rero-ils#1383
If a patron is blocked for any reasons, this user shouldn't be able to
extend any active loan.

Closes rero/rero-ils#1507
Fixes 'status' facet problem on items result list. Despite if user
select a status facet to filter the results, the facet value didn't
apply.
```
No trailing dot on commit title.

2020-11-26 07:33 UTC, lauren-d commented on rero_ils/modules/patrons/api.py
> +        return cls.can_request(item, **kwargs)
maybe you can explain in comment why `can_checkout` returns result of `can_request` or create a new function based on `can_request` logic

2020-11-26 07:33 UTC, lauren-d commented on rero_ils/modules/patrons/api.py
> +        return cls.can_request(item, **kwargs)
same as previous comment.

2020-11-26 07:45 UTC, lauren-d approved these changes

2020-11-30 08:12 UTC, iGormilhit approved these changes

2020-11-30 09:08 UTC, merged