users: display keep_history setting in public interface
rero/rero-ils pull request #1512
Opened 2020-11-26 14:14 UTC by BadrAly

Anonymize loans after patron updates.

    Co-Authored-by: [Your Full Name] <[your-email]>
    Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2020-11-30 12:27 UTC, iGormilhit requested changes
Commit message proposition:

```
users: allow to edit keep_history setting

* Adds the `keep_history` field to the list of fields editable by the
  user in the RERO ID form.
* Adds an 'edit' button to allow user to edit his profile from the
  Personal data tab.
* Anonymizes loans once the patron sets the field keep_history to false.
```

2020-12-01 06:42 UTC, Garfield-fr approved these changes

2020-12-01 07:09 UTC, iGormilhit approved these changes

2020-12-01 15:01 UTC, zannkukai requested changes

2020-12-01 15:01 UTC, zannkukai commented on rero_ils/modules/patrons/api.py
> +        self. _anonymize_loans(
is there a space between '.' and '_' ?
As `_anonymize_loans` is a class method, it's better/required to call it with `Patron._anonymize_loans`(not self)

2020-12-01 15:56 UTC, lauren-d approved these changes

2020-12-02 17:18 UTC, merged