interface: professional access
rero/rero-ils pull request #1520
Opened 2020-11-30 10:00 UTC by Garfield-fr

When a user doesn't have a patron record, we display a message "Permission required".

* Closes #1508

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2020-11-30 10:23 UTC, iGormilhit requested changes
Commit message proposition:

```
permissions: fix error message for users 

When a user that doesn't have the patron, librarian or system librarian
role, the message "Permission required" is displayed instead of
"Internal server error".

* Closes #1508
```

2020-11-30 12:28 UTC, iGormilhit approved these changes

2020-11-30 17:19 UTC, zannkukai approved these changes

2020-12-01 06:48 UTC, BadrAly approved these changes

2020-12-01 06:49 UTC, merged