vendor: remove form options on currency
rero/rero-ils pull request #1536
Opened 2020-12-02 10:06 UTC by Garfield-fr

Do not translate the currency symbols options of a select.

* closes #1519

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2020-12-03 06:57 UTC, iGormilhit requested changes
Commit message minor corrections:

```
vendors: do not translate currency codes

* Closes #1519.
```

2020-12-03 15:33 UTC, iGormilhit approved these changes

2020-12-04 07:52 UTC, lauren-d approved these changes

2020-12-07 15:54 UTC, zannkukai approved these changes

2020-12-08 08:01 UTC, merged