item: fix serials claims task
rero/rero-ils pull request #1546
Opened 2020-12-07 11:36 UTC by lauren-d

When an error is encountered on processing serials claims, the task
stops prematuraly. Late or claimed issues are not processed.

* Adds try statement to catch and log the error.

Co-Authored-by: Lauren-D <laurent.dubois@itld-solutions.be>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2020-12-07 14:05 UTC, benerken approved these changes

2020-12-07 16:02 UTC, zannkukai approved these changes

2020-12-09 06:51 UTC, BadrAly approved these changes

2020-12-09 07:25 UTC, iGormilhit requested changes
Commit message proposition:

```
serials: fix claim task

When an error is encountered on processing serials claims, the task
stops prematurely. Late or claimed issues are not processed.

* Adds a try statement to catch and log the error.
```

2020-12-09 07:46 UTC, iGormilhit approved these changes

2020-12-09 08:27 UTC, merged