profile: better management for fee document title
rero/rero-ils pull request #1548
Opened 2020-12-08 09:14 UTC by zannkukai

Into the patron profile page for 'fees' tab, sometime the document title
linked to a fees was not displayed. This commit improves the management
of document title using the general function `create_title_text` already
used to display the document title into the document detailed view.

Closes rero/rero-ils#1543

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## How to test?

- Login as a patron. 
- Go into the patron profile page
- Choose the fees tab
- Check the document title linked to the fee was correctly displayed

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2020-12-08 09:34 UTC, benerken approved these changes

2020-12-08 12:59 UTC, lauren-d approved these changes

2020-12-09 07:01 UTC, iGormilhit requested changes
Commit message proposition:

```
patrons: fix document title in the fees tab

In the 'fees' tab of the patron account, sometimes the document title
linked to a fee is not displayed. This commit improves the management of
document title using the general function `create_title_text`, which is
already used to display the document title on the document detailed
view.

Closes rero/rero-ils#1543.
```
I'm not super confident in my proposition, so if you think it's bad, tell me.

2020-12-09 07:05 UTC, Garfield-fr approved these changes

2020-12-09 13:24 UTC, merged