document: login button more visible
rero/rero-ils pull request #1556
Opened 2020-12-10 12:23 UTC by zannkukai

Aligns the login button (displayed on document detailed view, when users
are not yet connected) to the right of the screen to improve it
visibility and aligns it with other buttons (request, extend).

Closes rero/rero-ils#1473

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

![image](https://user-images.githubusercontent.com/10031585/101771847-d548ac00-3aea-11eb-98bf-e4327632af64.png)

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2020-12-11 06:44 UTC, benerken approved these changes

2020-12-11 07:40 UTC, lauren-d approved these changes

2020-12-14 06:58 UTC, iGormilhit requested changes
Commit message proposition:

```
documents: increase login button visibility

Aligns the login button (displayed on document detailed view, when users
are not yet connected) to the right of the screen to improve its
visibility and to align it with other buttons (request, extend).

Closes rero/rero-ils#1473.
```

2020-12-14 07:16 UTC, BadrAly approved these changes

2020-12-15 06:44 UTC, iGormilhit approved these changes

2021-01-06 15:47 UTC, merged