users: the communication email can be a secondary address
rero/rero-ils pull request #1561
Opened 2020-12-14 10:13 UTC by jma

* Makes the main address email optional if patron communication channel
  is email and the additional address email is defined.
* Adds a backend custom validation for this specific case.
* Closes #1499.

Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2020-12-14 12:16 UTC, lauren-d approved these changes

2020-12-14 16:16 UTC, BadrAly approved these changes

2020-12-15 06:28 UTC, iGormilhit requested changes
Commit message title proposition: `users: allows the 2nd email to be the only one`.

2020-12-15 06:46 UTC, iGormilhit approved these changes

2020-12-15 09:39 UTC, benerken approved these changes

2020-12-15 09:43 UTC, merged