import: fix author facet
rero/rero-ils pull request #1572
Opened 2020-12-16 20:54 UTC by rerowep

* closes #1564

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2020-12-17 06:57 UTC, iGormilhit requested changes
Commit message proposition:

```
search: fix author facet of BnF import search view

* Closes #1571.
* Fixes unimarc_series_statement creation crash.

```

2020-12-17 09:26 UTC, zannkukai approved these changes

2021-01-06 12:53 UTC, BadrAly approved these changes

2021-01-11 13:14 UTC, iGormilhit requested changes
Commit message proposition:

```
search: fix author facet of BnF import search view

* Closes #1571.
* Fixes the crash at unimarc_series_statement creation.
* Adds language facet.
```
(No PR dependency mention in the commit message. You can put it in the PR comment.

2021-01-11 13:22 UTC, iGormilhit approved these changes

2021-01-14 13:54 UTC, merged