es: settings template
rero/rero-ils pull request #1582
Opened 2020-12-28 19:35 UTC by rerowep

* Adds an setting template for elasticsearch with `number_of_shards`, `number_of_replicas` and `max_result_window`.
* Cleans all other elastic search mapping files.

Co-Authored-by:  Peter Weber <Peter.Weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-01-06 11:58 UTC, zannkukai approved these changes

2021-01-13 07:02 UTC, iGormilhit requested changes
Commit message proposition:

```
search: improve ES template for configuration

* Adds `number_of_shards`, `number_of_replicas` and `max_result_window`
  to record.json template.
* Cleans all other ElasticSearch mapping files.
```

2021-01-13 13:34 UTC, jma requested changes

2021-01-13 13:34 UTC, jma commented on rero_ils/modules/items/api/circulation.py
> +        # kwargs['transaction_date'] = datetime.now(timezone.utc).isoformat()
you can remove this

2021-01-13 13:34 UTC, jma commented on rero_ils/modules/items/api/circulation.py
> +        kwargs['transaction_date'] = datetime.utcnow().isoformat()
please mention this in the commit message

2021-01-13 13:34 UTC, jma commented on tests/ui/circulation/test_inhouse_cipo.py
> +    # TODO: find a way for the test will work also after 23:00
please mention this in the commit message

2021-01-13 13:53 UTC, AoNoOokami approved these changes

2021-01-14 06:07 UTC, iGormilhit approved these changes
Commit message approved.

2021-01-14 07:54 UTC, jma approved these changes

2021-01-14 08:47 UTC, merged