tests: fix poetry dependencies
rero/rero-ils pull request #1587
Opened 2021-01-04 15:23 UTC by AoNoOokami

* Adds py dependency.
* Adds a constraint fo jsonpickles.

Co-Authored-by: Alicia Zangger <alicia.zangger@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-01-05 14:14 UTC, rerowep requested changes

2021-01-05 14:14 UTC, rerowep commented on pyproject.toml
> +py = "^1.10.0"
`py` is not a direct dependency in our code. It is better to add a TODO with a reason why we added it , so we can delete this line later. Why the version must be fixed to `1.10.0`, Would it not be better if we say `>=1.10.0`?

2021-01-06 09:26 UTC, Garfield-fr approved these changes

2021-01-06 09:28 UTC, zannkukai approved these changes

2021-01-06 09:30 UTC, benerken approved these changes

2021-01-06 09:31 UTC, merged