search bar: Adapting the content according to the language
rero/rero-ils pull request #1588
Opened 2021-01-05 14:56 UTC by Garfield-fr

The suggestions in the auto-complete search bar
presents the data according to the current language.

- closes rero/rero-ils#1509

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

*https://github.com/rero/rero-ils-ui/pull/481

## How to test?

- Test search bar with different language and show translated suggestions.

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-01-13 07:06 UTC, iGormilhit requested changes
Commit message proposition:

```
search: adapt suggestions to the locale

- Presents the suggestions as the query is typed to the user defined
  locale.
- Closes rero/rero-ils#1509.
```

2021-01-26 07:00 UTC, jma approved these changes

2021-01-26 12:40 UTC, iGormilhit approved these changes

2021-01-26 12:41 UTC, BadrAly approved these changes

2021-01-26 15:54 UTC, merged