item: automatic barcode generation
rero/rero-ils pull request #1590
Opened 2021-01-06 13:32 UTC by zannkukai

Set the barcode field as not required field. If an item is
created/updated without barcode, the backend will generated a fictive
barcode itself.

Closes rero/rero-ils#1287

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## How to test?

- receive an serial issue in the UI interface (not using quick recieve)
- don't fill the barcode field
- change any other field in the form
- save the item
- check the created item has a fictive barcode ("f-2021....")

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-01-07 08:50 UTC, benerken approved these changes

2021-01-07 10:40 UTC, BadrAly approved these changes

2021-01-13 06:58 UTC, iGormilhit requested changes
Commit message proposition:

```
items: improve automatic barcode generation

Set the barcode field as optional. If an item is created/updated
without barcode, the backend will generated a fictive barcode itself.

Closes rero/rero-ils#1287.
Closes rero/rero-ils#1565.
```

2021-01-14 06:24 UTC, iGormilhit approved these changes

2021-01-14 12:53 UTC, merged