test: add tests for document creation
rero/rero-ils pull request #1595
Opened 2021-01-08 15:42 UTC by AoNoOokami

* Add tests to check document creation field by field.

Co-Authored-by: Alicia Zangger <alicia.zangger@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-02-10 06:40 UTC, iGormilhit requested changes

2021-02-10 06:40 UTC, iGormilhit commented on tests/e2e/cypress/cypress/integration/editor/document/create-document-prov-activity.spec.js
> +Copyright (C) 2020 RERO
```suggestion
Copyright (C) 2021 RERO
```

2021-02-10 06:40 UTC, iGormilhit commented on tests/e2e/cypress/cypress/integration/editor/document/create-document-resp-statement.spec.js
> +Copyright (C) 2020 RERO
```suggestion
Copyright (C) 2021 RERO
```

2021-02-10 06:40 UTC, iGormilhit commented on tests/e2e/cypress/cypress/integration/editor/document/create-document-simple-fields.spec.js
> +Copyright (C) 2020 RERO
```suggestion
Copyright (C) 2021 RERO
```

2021-02-10 17:10 UTC, zannkukai approved these changes

2021-02-11 06:57 UTC, iGormilhit approved these changes

2021-02-11 08:30 UTC, benerken approved these changes

2021-02-22 11:11 UTC, merged