documents: index holdings fields into document index
rero/rero-ils pull request #1628
Opened 2021-01-21 16:23 UTC by BadrAly

The following holdings fields are now indexed in the document index:

    * holdings.call_number
    * holdings.second_call_number
    * holdings.index
    * holdings.enumerationAndChronology
    * holdings.supplementaryContent
    * holdings.notes

    Co-Authored-by: Aly Badr <aly.badr@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-01-22 06:05 UTC, Garfield-fr approved these changes

2021-01-22 09:28 UTC, pronguen approved these changes

2021-01-22 14:12 UTC, benerken approved these changes

2021-01-25 06:44 UTC, iGormilhit requested changes
Commit message proposition. Check if my changes make sense.

```
documents: add to index some holdings fields

The following holdings fields are now indexed in the document index in
order to allow search requests on holdings data:

* holdings.call_number
* holdings.second_call_number
* holdings.index
* holdings.enumerationAndChronology
* holdings.supplementaryContent
* holdings.notes
```

2021-01-25 07:23 UTC, iGormilhit approved these changes

2021-01-25 11:12 UTC, merged