test: fix test in house
rero/rero-ils pull request #1644
Opened 2021-01-26 19:55 UTC by zannkukai

Fixes the test 'test_less_than_one_day_checkout'. If the test was
executed when the library is closed, the test failed ; So to fix this
problem, we freeze the transaction date to an opening day/hour.

Fixes the function `library.next_open()` function. This function didn't
care about hour/minutes.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-01-26 22:27 UTC, rerowep approved these changes
There should be a issue for this error, if you find it you can add `closes` to your commit message.

2021-01-27 05:51 UTC, iGormilhit requested changes
Commit message proposition:

```
test: fix the in house test

* Fixes the test 'test_less_than_one_day_checkout' that is failing if
  the test is executed when the library is closed. To fix this issue,
  the transaction date is frozen to an opening day/hour.
* Takes into account the hours and minutes in the `library.next_open()`
  function.
```

2021-01-27 06:39 UTC, benerken approved these changes

2021-01-27 09:45 UTC, AoNoOokami approved these changes

2021-01-27 09:50 UTC, BadrAly approved these changes

2021-01-27 10:26 UTC, merged