notification: create list of template API.
rero/rero-ils pull request #1650
Opened 2021-01-27 15:13 UTC by zannkukai

Creates an API entry point to list all templates available for
notification creation. Only template directories containing files
according to the configuration setting will be considerate as valid.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## How to test?

- call `https://localhost:5000/notifications/templates/list` url (logged as librarian/syslib)

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-01-29 07:06 UTC, Garfield-fr approved these changes

2021-02-01 07:58 UTC, iGormilhit requested changes
Commit message proposition, minor changes:

```
notifications: create an API to list templates

Creates an API entry point to list all templates available for
notification creation. Only template directories containing files
according to the configuration setting will be considered as valid.
```

- In the title:
    - *notifications* (plural).
    - No trailing dot.
- In the message body, *considered* instead of *considerate*.

2021-02-01 07:58 UTC, iGormilhit commented on tests/api/notifications/test_notifications_rest.py
> +    """test notification templates list API."""
```suggestion
    """Test notification templates list API."""
```

2021-02-02 07:00 UTC, BadrAly approved these changes

2021-02-02 11:00 UTC, iGormilhit approved these changes

2021-02-02 12:47 UTC, lauren-d approved these changes

2021-02-02 12:54 UTC, rerowep reviewed
Nice, but why we need this?

2021-02-02 13:35 UTC, merged