user: adds user info API
rero/rero-ils pull request #1656
Opened 2021-02-01 10:01 UTC by jma

* Adds a new API `/api/user_info/<username_or_email>` to get the
  information of a potential future patron or professional.

Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-02-01 17:34 UTC, BadrAly approved these changes

2021-02-02 08:18 UTC, lauren-d approved these changes

2021-02-02 11:02 UTC, iGormilhit requested changes
Commit message title: `users: add user info API` (users, plural, add infinitive form).

2021-02-02 11:02 UTC, iGormilhit commented on tests/api/test_users.py
> +# Copyright (C) 2019 RERO
```suggestion
# Copyright (C) 2021 RERO
```

2021-02-02 14:34 UTC, jma commented on tests/api/test_users.py
> +# Copyright (C) 2019 RERO
sorry

2021-02-02 15:30 UTC, merged