ui: fix login button
rero/rero-ils pull request #1663
Opened 2021-02-02 09:57 UTC by rerowep

* closes #1639

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-02-02 10:05 UTC, zannkukai approved these changes

2021-02-02 10:05 UTC, Garfield-fr approved these changes

2021-02-02 10:46 UTC, iGormilhit requested changes
Commit changes:

```
public ui: fix login button on holdings section

* Closes #1639.
```

2021-02-02 10:59 UTC, lauren-d approved these changes

2021-02-03 06:16 UTC, iGormilhit approved these changes

2021-02-03 08:07 UTC, merged