Maj patron rero id link
rero/rero-ils pull request #1667
Opened 2021-02-02 14:00 UTC by jma

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-02-03 15:25 UTC, lauren-d approved these changes

2021-02-03 15:25 UTC, lauren-d commented on tests/unit/test_patrons_jsonschema.py
> +#         validate(patron_martigny_data_tmp_with_id, patron_schema)
cosmetic: maybe you could notify why you comment that or simply remove this

2021-02-03 16:18 UTC, BadrAly approved these changes

2021-02-04 06:25 UTC, iGormilhit requested changes
One commit message proposition:

```
patrons: get user data from the profile

The user profiles is duplicated on the patron and profile record.  The
synchronization is done in the both direction, either when the user
change his/her profile or when a professional change the user
informations in the patron editor.

This commit changes this behavior. The data are modified only on the
profile database and synchronized in only one direction: from profile to
patron.

* Adds new utilities functions to support the current fixtures users
  data format.
* Removes all patron without email fixtures.
* Removes loans anonymization from the patron update/creation.
```

For the other one, just set `patrons` to the plural form.

2021-02-04 06:25 UTC, iGormilhit commented on rero_ils/modules/patrons/api.py
> +    :returns: - A Patron instance.
I'm not aware of the docstring format, but I'm wondering why the last one is a sentence (capital and dot) and note the three precedent lines.

2021-02-04 12:10 UTC, merged