circulation: implement incremental fees
rero/rero-ils pull request #1669
Opened 2021-02-02 17:15 UTC by zannkukai

* Adds method on `Loan` resource to compute incremental fees if the loan
  is in overdue.
* Adds an API entry point to preview the due fees when the loan will be
  returned.
* Updates check-in process to compute and saved the fees if the loan is
  in overdue.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-02-04 06:48 UTC, iGormilhit approved these changes

2021-02-04 10:16 UTC, benerken approved these changes

2021-02-05 08:06 UTC, lauren-d requested changes

2021-02-05 08:06 UTC, lauren-d commented on rero_ils/modules/loans/api_views.py
> +def holding_availability(loan_pid):
could you rename this method ? (probably a copy/paste)

2021-02-05 08:06 UTC, lauren-d commented on rero_ils/modules/loans/utils.py
> +    :param fee_steps: an array of tuples. Each first tupleelement should be
typo: missing space in `tupleelement`

2021-02-09 08:30 UTC, lauren-d approved these changes

2021-02-11 07:26 UTC, BadrAly approved these changes

2021-02-16 15:16 UTC, merged