users: add new resource
rero/rero-ils pull request #1675
Opened 2021-02-04 13:59 UTC by BadrAly

* Adds a new resource to manage the user profiles.
* Writes an API to manage user creations and updates.
* Create units testing.

Co-Authored-by: Aly Badr <aly.badr@rero.ch>
Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-02-05 22:16 UTC, rerowep requested changes

2021-02-05 22:16 UTC, rerowep commented on rero_ils/modules/users/api.py
> +        data['metadata'][field] = self.user.email
Schould it be `data['metadata']['email'] = self.user.email`

2021-02-05 22:16 UTC, rerowep commented on rero_ils/modules/users/api.py
> +        schema = data.pop('$schema', None)
Does the validation function correctly? In the schema file the `$schema` is a required field?

2021-02-05 22:16 UTC, rerowep commented on rero_ils/modules/users/jsonschemas/users/user-v0.0.1.json
> +      "minLength": 9,
Pattern validation should be nicer.
`"pattern": "^https://ils.rero.ch/schemas/users/*$"`

2021-02-05 22:16 UTC, rerowep commented on rero_ils/modules/users/jsonschemas/users/user-v0.0.1.json
> +}
No newline at end of file.

2021-02-08 10:56 UTC, BadrAly commented on rero_ils/modules/users/api.py
> +        db.session.commit()
`db.session.commit()` is needed.

2021-02-08 10:56 UTC, BadrAly commented on rero_ils/modules/users/api.py
> +        db.session.commit()
`db.session.commit()` is needed.

2021-02-10 06:13 UTC, iGormilhit requested changes
Commit message proposition:

```
users: add new resource

* Adds a new 'user' resource to manage the user profiles. It contains
  the user personal data as opposed to the patron data that are link to
  a specific organisation.
* Writes an API to manage user creations and updates.
* Create units testing.
```

2021-02-10 12:49 UTC, jma commented on rero_ils/modules/users/api.py
> +        email = data.pop('email', None)
Yes the email is on the User database and not on the profile. The schema is only for the profile.

2021-02-11 06:49 UTC, iGormilhit requested changes
New commit message proposition:

```
users: add new resource

* Adds a new 'user' resource to manage the user profiles. It contains
  the user personal data as opposed to the patron data that are link to
  a specific organisation.
* Writes a REST API:
  * A GET, POST, PUT methods to create, update and retrieves the patron
    personal information.
  * A search endpoint to retrieve the patron personal information given
    an email or a username.
* Creates units testing.
* Centralizes several views and methods in a specific `User` python
  class.
* Disables the validation email for freshly created user.
* Uses the standard ngx-formly `widget` field for the user JSON schema.
```
Formatting, some minor typos, slighlty reworded.

2021-02-11 12:15 UTC, lauren-d approved these changes

2021-02-11 12:54 UTC, rerowep approved these changes

2021-02-11 13:14 UTC, iGormilhit approved these changes

2021-02-11 14:03 UTC, merged