monitoring: elastic search
rero/rero-ils pull request #1694
Opened 2021-02-11 10:40 UTC by rerowep

* Adds elastic search cluster monitoring.

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-02-11 13:18 UTC, rerowep commented
> Why do you need to build an api for doing that?
> You could directly call ES api with `/_cluster/health` or `/_cluster/health/?level=shards`

I know, it is for grouping all monitoring in one place for rero-ils. This way you always have the associated servies in one place.

2021-02-11 14:08 UTC, lauren-d approved these changes

2021-02-22 07:27 UTC, jma approved these changes

2021-02-23 07:09 UTC, BadrAly approved these changes

2021-02-23 08:07 UTC, zannkukai approved these changes

2021-02-23 10:44 UTC, sebastiendeleze approved these changes

2021-02-24 15:33 UTC, iGormilhit requested changes
Message proposition:

```
monitoring: configure ElasticSearch monitoring

* Configures the monitoring of the ElasticSearch cluster.
```

2021-02-25 06:00 UTC, iGormilhit approved these changes
Commit message approved.

2021-02-25 07:25 UTC, merged