Request: fix permissions
rero/rero-ils pull request #1714
Opened 2021-02-22 14:10 UTC by zannkukai

If the current user had role librarian AND role patron, it couln't
view/edit an ILL requests into the admin interface.

Closes rero/rero-ils#1709.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-02-22 16:19 UTC, benerken approved these changes

2021-02-23 07:45 UTC, AoNoOokami commented on rero_ils/modules/ill_requests/permissions.py
> +            # patron an only read their own requests
can?

2021-02-23 07:53 UTC, iGormilhit requested changes
Commit message proposition:

```
ILL request: fix permissions

* Fixes permissions when the current user has librarian AND patron
  roles, thus preventing him or her to view/edit an ILL requests on the
  professional interface.
* Closes rero/rero-ils#1709.
```

2021-02-25 15:08 UTC, rerowep approved these changes

2021-03-03 13:14 UTC, lauren-d approved these changes

2021-03-03 13:15 UTC, merged