document: fix processing of title field
rero/rero-ils pull request #1760
Opened 2021-03-11 07:42 UTC by Garfield-fr

* Closes #1745.

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-03-11 11:36 UTC, benerken approved these changes

2021-03-11 13:05 UTC, zannkukai requested changes

2021-03-11 13:05 UTC, zannkukai commented on rero_ils/modules/documents/utils.py
> +        main_title_output[language].append(value)
```main_title_output.setdefault(language, []).append(value)```

2021-03-11 13:05 UTC, zannkukai commented on rero_ils/modules/documents/utils.py
> +            subtitle_output[language].append(value)
```subtitle_output.setdefault(language, []).append(value)```

2021-03-12 08:28 UTC, zannkukai approved these changes

2021-03-14 16:16 UTC, rerowep approved these changes

2021-03-16 14:05 UTC, merged