SRU: json to marc21
rero/rero-ils pull request #1833
Opened 2021-04-16 08:45 UTC by rerowep

* Adds dojson for json to marc21 transformation.

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-05-04 05:28 UTC, iGormilhit requested changes
Commit message proposition:

```
SRU: convert JSON to MARC21

* Adds dojson for JSON to MARC21 transformation.
```

2021-05-04 05:28 UTC, iGormilhit commented on rero_ils/modules/documents/dojson/contrib/jsontomarc21/__init__.py
> +# Copyright (C) 2019 RERO
```suggestion
# Copyright (C) 2021 RERO
```

2021-05-04 05:28 UTC, iGormilhit commented on rero_ils/modules/documents/dojson/contrib/jsontomarc21/__init__.py
> +"""MARC21 RERO to JSON."""
```suggestion
"""RERO MARC21 to JSON."""
```

2021-05-04 05:28 UTC, iGormilhit commented on rero_ils/modules/holdings/api.py
>          """Returns holding pids by document and view code."""
```suggestion
        """Returns holding PIDs by document and view code."""
```

If it's not too much an hassle, change all pid in PID and pids in PIDs in the docstrings. It's easier to read and understand.

2021-05-04 05:28 UTC, iGormilhit commented on tests/unit/test_documents_dojson_marc21.py
> +# Copyright (C) 2019 RERO
```suggestion
# Copyright (C) 2021 RERO
```

2021-05-04 05:28 UTC, iGormilhit commented on tests/unit/test_documents_dojson_marc21.py
> +"""DOJSON transiformation for ebooks module tests."""
```suggestion
"""DOJSON transformation for ebooks module tests."""
```

2021-05-04 05:28 UTC, iGormilhit commented on tests/unit/test_documents_dojson_marc21.py
> +    """Test pidto marc21 transformation."""
```suggestion
    """Test PID to MARC21 transformation."""
```

2021-05-04 05:28 UTC, iGormilhit commented on tests/unit/test_documents_dojson_marc21.py
> +    """Test titleto marc21 transformation."""
```suggestion
    """Test title to MARC21 transformation."""
```

2021-05-04 05:28 UTC, iGormilhit commented on tests/unit/test_documents_dojson_marc21.py
> +    """Test contributionto marc21 transformation."""
```suggestion
    """Test contribution to MARC21 transformation."""
```

2021-05-04 05:28 UTC, iGormilhit commented on tests/unit/test_documents_dojson_marc21.py
> +    """Test type to marc21 transformation."""
```suggestion
    """Test type to MARC21 transformation."""
```

2021-05-04 05:28 UTC, iGormilhit commented on tests/unit/test_documents_dojson_marc21.py
> +    """Test holding items to marc21 transformation."""
```suggestion
    """Test holding items to MARC21 transformation."""
```

2021-05-04 07:29 UTC, zannkukai requested changes

2021-05-04 07:29 UTC, zannkukai commented on rero_ils/modules/documents/dojson/contrib/jsontomarc21/model.py
> +                },
For each holding hit, you reload the organisation, the library, the location. But these informations should be load once and temporary store to improve speed. Something like :
```python
orgs = libraries = locations = {}
for hit in hits:
    holding = hit.to_dict()
    if hit.organisation.pid not in orgs:
        orgs[hit.organisation.pid] = get_name(Organisation, hit.organisation.pid)
    ...
    result = {
        'organisation': { 'pid': hit.organisation.pid, 'name': orgs[hit.organisation.pid]},
         ...
     }
     
```

2021-05-04 07:29 UTC, zannkukai commented on rero_ils/modules/documents/serializers.py
> +            self.dumps_kwargs = {}
maybe better :
```python
self.dump_kwargs = {}
if xslt_filename:
    self.dumps_kwargs['xslt_filename'] = xslt_filename```

2021-05-04 07:29 UTC, zannkukai commented on rero_ils/modules/documents/serializers.py
> +        return record
coud be merge into singe instruction : `return to_marc21.do(...)`

2021-05-04 07:29 UTC, zannkukai commented on rero_ils/modules/documents/serializers.py
> +        return record
same here

2021-05-10 05:22 UTC, iGormilhit approved these changes
Commit message approved.

2021-05-10 08:53 UTC, merged