serials: fix issue.status_date field update
rero/rero-ils pull request #1911
Opened 2021-05-11 05:42 UTC by zannkukai

* Ensure than the issue.status_date field is update when an issue is created/updated.
* Closes #1654.

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-05-11 06:05 UTC, iGormilhit requested changes
Commit message proposition:

```
serials: fix issue.status_date field update

* Ensure that the `issue.status_date` field is updated when an issue is
  created/updated.
* Closes rero#1654.

2021-05-11 07:01 UTC, lauren-d requested changes

2021-05-25 05:30 UTC, iGormilhit approved these changes

2021-06-02 10:26 UTC, benerken approved these changes

2021-06-02 11:45 UTC, BadrAly approved these changes

2021-06-07 15:21 UTC, merged