notifications: adds library notifications
rero/rero-ils pull request #1914
Opened 2021-05-11 10:25 UTC by Garfield-fr

* Adds new notifications: booking, request and transit notice.
* Adds a communication language for the libraries notifications.
* Adds comments and clean up the notifications creation code.
* Uses a class property for notification types instead of a string in
  the code.
* Enhance some formatted strings.
* Adds new notification templates in 4 languages.
* Removes old location based notifications (paging request).
* Removes useless debug printing instructions.
* Adds a new function to convert an ISO639-2 into an ISO639-1 language
  code using the iso639 python package.
* Removes useless cli command.
* Removed the useless pycountry package dependency.

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>
Co-Authored-by: Johnny Mariéthoz <johnny.mariethoz@rero.ch>

## Dependencies

My PR depends PR(s):
- https://github.com/rero/rero-ils-ui/pull/606

## Why are you opening this PR?

- https://tree.taiga.io/project/rero21-reroils/us/1229?milestone=291300

## How to test?

- ! This replace an old implementation: (paging request)

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-05-12 07:28 UTC, iGormilhit requested changes
A verb is missing in the commit message title.

2021-05-31 06:32 UTC, lauren-d approved these changes

2021-05-31 06:32 UTC, lauren-d commented on rero_ils/modules/loans/api.py
> +        ):
Could be replaced by :
```python
if notif_type in [
           Notification.TRANSIT_NOTICE_NOTIFICATION_TYPE,
           Notification.BOOKING_NOTIFICATION_TYPE,
           Notification.REQUEST_NOTIFICATION_TYPE]:
```

2021-05-31 08:34 UTC, rerowep approved these changes

2021-05-31 09:13 UTC, iGormilhit approved these changes

2021-06-02 12:47 UTC, ManaDeweerdt commented
I'm not sure if it is linked or already reported but the 'destination' is missed from the transit message.
![image](https://user-images.githubusercontent.com/12396034/120482464-771dc700-c3b1-11eb-8dfd-ea0e5f0c530d.png)

2021-06-02 13:05 UTC, Garfield-fr commented
> I'm not sure if it is linked or already reported but the 'destination' is missing from the transit message.
> ![image](https://user-images.githubusercontent.com/12396034/120482464-771dc700-c3b1-11eb-8dfd-ea0e5f0c530d.png)

The text is not injected, because the translation is missing

2021-06-03 07:45 UTC, ManaDeweerdt commented
I don't understand very well the ''Removes old location based notifications (paging request).'' The field 'send notification' was still there at the location level.

2021-06-07 06:06 UTC, jma commented
> I don't understand very well the ''Removes old location based notifications (paging request).'' The field 'send notification' was still there at the location level.

We has an old paging request implementation. With this new US, I have re-implement this feature as it is  one of the 3 new notifications required by this new US. My comment was: please retest this feature as it has been rewritten.

2021-06-09 09:04 UTC, merged