SRU marc21 physical description & isbn
rero/rero-ils pull request #1939
Opened 2021-05-24 19:36 UTC by rerowep

* Adds JSON to MARC21 physical description transformation.
 * Adds JSON to MARC21 ISBN transformation.
    
## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-05-25 05:02 UTC, iGormilhit requested changes
Commit title: SRU capitalized, do not forget a verb.

Some comments are on the previous commit, sorry. Should be corrected on https://github.com/rero/rero-ils/pull/1834.

2021-05-25 05:02 UTC, iGormilhit commented on rero_ils/modules/sru/explaine.py
> +# Copyright (C) 2020 UCLouvain
```suggestion
# Copyright (C) 2021 RERO
# Copyright (C) 2021 UCLouvain
```

2021-05-25 05:02 UTC, iGormilhit commented on rero_ils/modules/sru/views.py
> +# Copyright (C) 2019 RERO
```suggestion
# Copyright (C) 2021 RERO
```

2021-05-25 05:02 UTC, iGormilhit commented on tests/api/sru/test_sru_rest.py
> +# Copyright (C) 2019 RERO
```suggestion
# Copyright (C) 2021 RERO
```

2021-05-25 05:02 UTC, iGormilhit commented on tests/unit/test_cql_parser.py
> +# Copyright (C) 2019 RERO
```suggestion
# Copyright (C) 2021 RERO
```

2021-05-25 05:02 UTC, iGormilhit commented on tests/unit/test_sru_explain.py
> +# Copyright (C) 2019 RERO
```suggestion
# Copyright (C) 2021 RERO
```

2021-05-25 19:47 UTC, rerowep commented on rero_ils/modules/documents/dojson/contrib/jsontomarc21/__init__.py
> +"""JSON to MARC21."""
Generic

2021-05-25 19:52 UTC, rerowep commented on rero_ils/modules/documents/dojson/contrib/jsontomarc21/__init__.py
> +"""JSON to MARC21."""
Generic

2021-05-26 06:42 UTC, zannkukai approved these changes

2021-05-31 08:05 UTC, merged