utils: add json writer
rero/rero-ils pull request #1941
Opened 2021-05-25 12:43 UTC by rerowep

* Adds JsonWriter class to write json data well formatted to a file.

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-05-26 04:57 UTC, iGormilhit requested changes
Commit message:

```
CLI: add a JSON writer

* Adds a `JsonWriter` class to write well formatted JSON data into a file.
```

2021-05-26 04:57 UTC, iGormilhit commented on rero_ils/modules/utils.py
> +        :params filename: file name of write file.
File name of the file to be written? File name of the written file? Something else?

2021-05-26 04:57 UTC, iGormilhit commented on rero_ils/modules/utils.py
> +        :param indent: indention.
```suggestion
        :param indent: indentation.
```

2021-05-26 04:57 UTC, iGormilhit commented on rero_ils/modules/utils.py
> +        :param data: json data to write.
```suggestion
        :param data: JSON data to write into the file.
```

2021-05-26 06:44 UTC, zannkukai approved these changes

2021-05-27 05:52 UTC, iGormilhit approved these changes

2021-05-27 07:25 UTC, lauren-d approved these changes

2021-05-27 11:21 UTC, merged