fix: empty list in function parameters
rero/rero-ils pull request #1953
Opened 2021-05-27 12:13 UTC by rerowep

* https://docs.python-guide.org/writing/gotchas/

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-05-28 08:20 UTC, zannkukai approved these changes
Great job

2021-05-31 05:44 UTC, iGormilhit requested changes
Fix isn't a component. There's no verb in the commit message title.

2021-05-31 06:12 UTC, lauren-d approved these changes

2021-05-31 14:56 UTC, sebastiendeleze approved these changes

2021-05-31 14:56 UTC, sebastiendeleze commented on rero_ils/modules/ebooks/receivers.py
> +        records = list(records)[:int(max)]
Is it really necessary?

2021-06-02 10:21 UTC, benerken approved these changes

2021-06-02 11:36 UTC, iGormilhit approved these changes

2021-06-02 11:45 UTC, merged