templates: adapt document complete schema
rero/rero-ils pull request #1960
Opened 2021-05-31 12:06 UTC by rerowep

* Adapts fixtures for document templates to work correctly with the
  complete JSON schema.
* Closes #1905.

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-05-31 12:50 UTC, iGormilhit requested changes
Commit message proposition:

```
fixtures: adapt templates to complete data model 

* Adapts fixtures for document templates to work correctly with the
  complete JSON schema.
* Closes #1905.
```

2021-05-31 14:52 UTC, sebastiendeleze approved these changes

2021-06-01 12:31 UTC, zannkukai approved these changes

2021-06-02 10:25 UTC, iGormilhit approved these changes

2021-06-02 10:48 UTC, merged