translation: add USER_DOES_NOT_EXIST and remove prefix
rero/rero-ils pull request #1963
Opened 2021-05-31 14:47 UTC by rerowep

* Adds `USER_DOES_NOT_EXIST` to translations.
* Removes `{prefix}{key}`, `{prefix}{item}` and `{prefix}{data}` from
  translation.

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-06-01 12:31 UTC, zannkukai approved these changes

2021-06-02 06:22 UTC, iGormilhit requested changes
Commit message proposition:

```
translations: fix minor issues 

* Extracts `USER_DOES_NOT_EXIST` string.
* Removes `{prefix}{key}`, `{prefix}{item}` and `{prefix}{data}` from
  translations.
```

2021-06-02 09:35 UTC, Garfield-fr approved these changes

2021-06-02 11:36 UTC, iGormilhit approved these changes

2021-06-02 11:45 UTC, merged