collection: fix item brief view.
rero/rero-ils pull request #1978
Opened 2021-06-04 11:50 UTC by zannkukai

If a collection not define a 'description' field, the item serializer
generate an error. This error cause a javascript failure when UI try to
display the item brief view related to this collection.

Closes rero/rero-ils#1942.

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-06-05 17:40 UTC, rerowep approved these changes

2021-06-07 04:55 UTC, iGormilhit requested changes
Commit message proposition:

```
collections: fix item brief view

If a collection has no 'description' field defined, the item serializer
generates an error, which cause a javascript failure when the UI tries to
display the item brief view related to this collection.
```
- Title: collections with an 's'.
- Title: no trailing dot.
- Body: some rewording.

2021-06-07 06:09 UTC, iGormilhit approved these changes

2021-06-07 07:06 UTC, Garfield-fr approved these changes

2021-06-07 15:09 UTC, benerken approved these changes

2021-06-07 15:16 UTC, merged