user profiles: translate username description
rero/rero-ils pull request #2001
Opened 2021-06-08 09:03 UTC by iGormilhit

* Translates the username description that comes from
  rero/invenio-userprofiles (`validators.py`).

Co-Authored-by: Igor Milhit <igor.milhit@rero.ch>

## Why are you opening this PR?

- A string is not extracted and translated because it comes from
  rero/invenio-userprofiles. 

## Dependencies

My PR depends on the following `rero/invenio-userprofiles`'s PR(s):

* rero/invenio-userprofiles#5

## How to test?

- Check if the string is extracted. 

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-06-08 10:38 UTC, Garfield-fr approved these changes

2021-06-09 07:19 UTC, jma requested changes

2021-06-09 07:19 UTC, jma commented on rero_ils/manual_translations.txt
> +_('Username must start with a letter or a number, be at least three characters'
space is missing. You will end with `characterslong` string.

2021-06-10 08:36 UTC, jma approved these changes

2021-06-10 08:36 UTC, merged