document: make document `mainTitle` unique
rero/rero-ils pull request #2024
Opened 2021-06-11 07:15 UTC by zannkukai

Adds a validator to make the document `mainTitle` unique (but only in
the UI editor context - not for document REST loading).

Closes rero/rero-ils#1361.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-06-11 13:00 UTC, benerken approved these changes

2021-06-13 06:23 UTC, rerowep requested changes
`ng-core` dev must be used to test this PR.

2021-06-14 07:02 UTC, iGormilhit reviewed
Commit message component: s/document/documents/ (with an s).

2021-06-14 08:07 UTC, jma approved these changes

2021-06-14 10:31 UTC, merged