holdings: remove standard holdings with no attached items
rero/rero-ils pull request #2044
Opened 2021-06-16 14:19 UTC by BadrAly

Following the recent changes to the item indexing, the feature
to automatically delete standard holdings with no items is disabled.

This commits puts back the removed logic as a cron job.

Co-Authored-by: Aly Badr <aly.badr@rero.ch>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-06-16 14:28 UTC, iGormilhit approved these changes

2021-06-16 14:28 UTC, zannkukai requested changes

2021-06-16 14:28 UTC, zannkukai commented on rero_ils/modules/holdings/tasks.py
> +        pass
You should benefits of the `item_count` ES key into `holding` index to execute a single query :
```python
es_query = HoldingsSearch() \
    .filter('term', holdings_type='standard') \       
    .filter('term', item_count=0) \
    .source('pid') \        
    .scan()
 for hit in es_query:
     holding = Holding.get_record_by_pid(hit.pid)
     record.delete(force=False, dbcommit=True, delindex=True)
     msg = f'Removing standard holdings pid: {holdings_pid}'
     current_app.logger.info(msg)
```

2021-06-17 09:29 UTC, benerken approved these changes

2021-06-17 18:41 UTC, rerowep requested changes

2021-06-17 18:41 UTC, rerowep commented on rero_ils/modules/holdings/tasks.py
> +    msg = 'Nothing to do'
This message is never used.

2021-06-17 18:41 UTC, rerowep commented on rero_ils/modules/holdings/tasks.py
> +    except Exception as err:
Why we need a `try except` here?

2021-06-17 18:41 UTC, rerowep commented on rero_ils/modules/holdings/tasks.py
> +        pass
If we have an exception it should be better to log it.

2021-06-17 18:41 UTC, rerowep commented on tests/ui/holdings/test_holdings_api.py
> +    hold = Holding.get_record_by_pid(holding_lib_martigny.pid)
Maybe better to get the holdings pid once and use it later.

2021-06-17 18:41 UTC, rerowep commented on tests/ui/holdings/test_holdings_api.py
> +    hold = Holding.get_record_by_pid(holding_lib_martigny.pid)
See above.

2021-06-21 05:42 UTC, iGormilhit reviewed
Commit message title too long: just remove the "attached" before "items".

2021-06-21 12:00 UTC, zannkukai approved these changes

2021-06-24 14:39 UTC, rerowep approved these changes

2021-06-25 06:52 UTC, merged