sip2: improve command line utilities
rero/rero-ils pull request #2069
Opened 2021-06-23 09:59 UTC by lauren-d

* Adds some CLI command to manage selfcheck terminals.

Co-Authored-by: Lauren-D <laurent.dubois@itld-solutions.be>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-06-24 05:12 UTC, iGormilhit reviewed
Commit message approved.

2021-06-24 05:12 UTC, iGormilhit commented on rero_ils/modules/selfcheck/cli.py
> +    """List all configured terminal."""
```suggestion
    """List all configured terminals."""
```

2021-06-25 05:48 UTC, lauren-d commented on rero_ils/modules/selfcheck/cli.py
> +    """List all configured terminal."""
ok. Done.

2021-06-26 11:15 UTC, rerowep requested changes
If I give a non existing user I get:
```
  File "//Users/peter/devel/virtualenvs/rero-ils-CoBhSWGK-py3.7/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'NoneType' object has no attribute 'id'
```
A message: User does not exist, would be better.

I'am not sure it is a valid use case but if I try to use the same user for a second terminal I get following warning:
```
WARNING (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_oauth2server_token_access_token"
DETAIL:  Key (access_token)=(\x58724f593842594f6e476c755242316579364a766e6f5350724b3469576e67695a7756467a7469484c57544e75784a677a4f724d34492f38785a67453568564d495a6d754d7345446e44316d6d69414b335a704a45413d3d) already exists.

[SQL: INSERT INTO oauth2server_token (client_id, user_id, token_type, access_token, refresh_token, expires, _scopes, is_personal, is_internal) VALUES (%(client_id)s, %(user_id)s, %(token_type)s, %(access_token)s, %(refresh_token)s, %(expires)s, %(_scopes)s, %(is_personal)s, %(is_internal)s) RETURNING oauth2server_token.id]
[parameters: {'client_id': '41ofFMveiwFuMxGadBPzIwMFlMSeZhszM7LkY8rj', 'user_id': 5, 'token_type': 'bearer', 'access_token': <psycopg2.extensions.Binary object at 0x106f5d270>, 'refresh_token': None, 'expires': None, '_scopes': '', 'is_personal': True, 'is_internal': False}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

2021-06-29 07:01 UTC, iGormilhit approved these changes

2021-06-30 07:37 UTC, lauren-d commented
> If I give a non existing user I get:
> 
> ```
>   File "//Users/peter/devel/virtualenvs/rero-ils-CoBhSWGK-py3.7/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
>     return getattr(self._get_current_object(), name)
> AttributeError: 'NoneType' object has no attribute 'id'
> ```
> 
> A message: User does not exist, would be better.

Done.

> I'am not sure it is a valid use case but if I try to use the same user for a second terminal I get following warning:
> 
> ```
> WARNING (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_oauth2server_token_access_token"
> DETAIL:  Key (access_token)=(\x58724f593842594f6e476c755242316579364a766e6f5350724b3469576e67695a7756467a7469484c57544e75784a677a4f724d34492f38785a67453568564d495a6d754d7345446e44316d6d69414b335a704a45413d3d) already exists.
> 
> [SQL: INSERT INTO oauth2server_token (client_id, user_id, token_type, access_token, refresh_token, expires, _scopes, is_personal, is_internal) VALUES (%(client_id)s, %(user_id)s, %(token_type)s, %(access_token)s, %(refresh_token)s, %(expires)s, %(_scopes)s, %(is_personal)s, %(is_internal)s) RETURNING oauth2server_token.id]
> [parameters: {'client_id': '41ofFMveiwFuMxGadBPzIwMFlMSeZhszM7LkY8rj', 'user_id': 5, 'token_type': 'bearer', 'access_token': <psycopg2.extensions.Binary object at 0x106f5d270>, 'refresh_token': None, 'expires': None, '_scopes': '', 'is_personal': True, 'is_internal': False}]
> (Background on this error at: http://sqlalche.me/e/13/gkpj)
> ```

it's corrected

2021-06-30 07:39 UTC, benerken approved these changes

2021-06-30 14:38 UTC, rerowep approved these changes

2021-07-01 06:07 UTC, merged