data: only one default circulation policy by organisation.
rero/rero-ils pull request #2078
Opened 2021-06-25 05:45 UTC by Garfield-fr

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-06-25 06:50 UTC, BadrAly approved these changes

2021-06-25 06:52 UTC, zannkukai approved these changes

2021-06-28 06:08 UTC, iGormilhit requested changes
Commit message title: `fixtures: allow only one circulation policy`

2021-06-29 07:21 UTC, iGormilhit approved these changes

2021-06-29 07:25 UTC, merged