notification: fix German availability template
rero/rero-ils pull request #2083
Opened 2021-06-28 06:54 UTC by rerowep

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-06-28 07:13 UTC, iGormilhit requested changes
Commit message proposition:

```
notifications: fix German availability template

* Fixes the display of the next opened day of the library.
```

In the title, notifications with an 's'.

2021-06-28 07:56 UTC, zannkukai reviewed
Are you sure ? For me the problem seems to be in other templates.
We're teellng that a book is available at a "pickup_location", it seems normal to use this "pickup_location" to determine the `next_open`

2021-06-28 10:32 UTC, rerowep commented
> Are you sure ? For me the problem seems to be in other templates.
> We're teellng that a book is available at a "pickup_location", it seems normal to use this "pickup_location" to determine the `next_open`

If I understand the code right, the library is the pickup_location:
```python
            if pickup_location:
                data['loan']['pickup_location'] = \
                    pickup_location.replace_refs().dumps()
                # del(data['loan']['pickup_location_pid'])
                library_pid = data['loan']['pickup_location']['library']['pid']
                library = Library.get_record_by_pid(library_pid)
                data['loan']['pickup_name'] = pickup_location['pickup_name']
                data['loan']['library'] = library
                # TODO: make availability days variable (fixed to 10 days)
                keep_until = datetime.now(timezone.utc) + timedelta(days=10)
                next_open = library.next_open(keep_until)
                # language = data['loan']['patron']['communication_language']
                next_open = next_open.strftime("%d.%m.%Y")
                data['loan']['library']['next_open'] = next_open
```

2021-06-28 12:25 UTC, zannkukai approved these changes

2021-06-29 04:39 UTC, Garfield-fr approved these changes

2021-06-29 05:54 UTC, iGormilhit approved these changes

2021-06-29 08:58 UTC, merged