document: better available
rero/rero-ils pull request #2084
Opened 2021-06-28 07:56 UTC by rerowep

* Makes document is_available more fault tolerant for holding problems.

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-06-28 08:14 UTC, iGormilhit requested changes
Commit message proposition:

```
documents: reinforce availability robustness

* Makes document availability handling more fault tolerant for holdings problems.
```

2021-06-28 12:29 UTC, zannkukai approved these changes
I begin to be very complex if we need to validate than ES data is consistent :'(

2021-06-28 12:41 UTC, iGormilhit approved these changes

2021-06-28 12:43 UTC, benerken approved these changes

2021-06-29 04:19 UTC, Garfield-fr approved these changes

2021-06-29 08:57 UTC, merged