circulation: fix check is loan overdue method
rero/rero-ils pull request #2114
Opened 2021-07-02 12:33 UTC by zannkukai

Closes rero/rero-ils#2014.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-07-05 06:09 UTC, iGormilhit requested changes
Commit message title proposition: `circulation: fix method for "is loan overdue" check`

2021-07-05 07:52 UTC, benerken approved these changes

2021-07-06 13:43 UTC, iGormilhit approved these changes

2021-07-06 13:57 UTC, BadrAly requested changes

2021-07-06 13:57 UTC, BadrAly commented on rero_ils/modules/loans/api.py
> +        .source(['pid', 'end_date']).scan()
why the `end_date` here?

2021-07-06 14:04 UTC, zannkukai commented on rero_ils/modules/loans/api.py
> +        .source(['pid', 'end_date']).scan()
it was for debug... forget to remove :(

2021-07-06 14:33 UTC, BadrAly approved these changes

2021-07-07 08:39 UTC, merged