users: fix creation cli.
rero/rero-ils pull request #2129
Opened 2021-07-07 15:55 UTC by rerowep

* Fixes users creation cli for data without pid.

Co-Authored-by: Peter Weber <ipeter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-07-07 15:59 UTC, benerken approved these changes

2021-07-07 16:07 UTC, sebastiendeleze approved these changes

2021-07-08 04:50 UTC, iGormilhit requested changes
Commit message proposition:

```
SIP2: fix CLI for user creation

* Fixes CLI for users creation for data without PID.
```

2021-07-08 08:48 UTC, iGormilhit approved these changes

2021-07-08 09:22 UTC, Garfield-fr approved these changes

2021-07-08 09:58 UTC, merged