operation_log: replace pid by value for operation_log indexing
rero/rero-ils pull request #2138
Opened 2021-07-09 13:03 UTC by BadrAly

* Fixes problem when old record pid is loaded into the operation_log es.

Co-Authored-by: Aly Badr <aly.badr@rero.ch>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-07-09 15:52 UTC, rerowep requested changes

2021-07-09 15:52 UTC, rerowep commented on rero_ils/modules/operation_logs/api.py
> +            if oplg.get('record', []).get('pid'):
I thing it should be:
`if oplg.get('record', {}).get('pid'):`

2021-07-11 20:53 UTC, rerowep approved these changes

2021-07-14 13:55 UTC, benerken approved these changes

2021-07-14 13:56 UTC, lauren-d approved these changes

2021-07-22 11:17 UTC, merged