operation logs: improve dump_operation_logs cli
rero/rero-ils pull request #2154
Opened 2021-07-13 08:41 UTC by rerowep

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-07-13 10:38 UTC, Garfield-fr approved these changes

2021-07-19 07:31 UTC, iGormilhit commented on rero_ils/modules/operation_logs/cli.py
> +    with click.progressbar(search.scan(), length=search.count()) as bar:
Could the commit message be more precise? Add the search count to the progress bar or something?

2021-07-19 12:30 UTC, jma approved these changes

2021-07-19 12:31 UTC, jma approved these changes

2021-07-19 12:33 UTC, iGormilhit requested changes
Commit message title proposition: `operation logs: add progress bar to `dump_operation_logs` CLI`

2021-07-19 12:59 UTC, iGormilhit approved these changes

2021-07-19 13:36 UTC, merged