locations: allow pickup locations sortering
rero/rero-ils pull request #2166
Opened 2021-07-14 10:15 UTC by zannkukai

Adds a configuration key to allow pickup locations sortering on the
item request form.
Closes rero/rero-ils#1899.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-07-22 05:45 UTC, iGormilhit requested changes
Commit message proposition:

```
locations: allow to sort pickup locations

* Adds a configuration key to set the pickup locations sort on the
   item request form.
* Closes rero#1899.
```

Is it possible to find a better file name for `test_locations_other.py`? :slightly_smiling_face:

2021-07-22 05:45 UTC, iGormilhit commented on rero_ils/modules/locations/utils.py
> +"""Utils function about locations."""
```suggestion
"""Utilities for locations."""
```

2021-09-21 09:26 UTC, Garfield-fr approved these changes

2021-09-22 17:36 UTC, lauren-d approved these changes

2021-09-22 20:05 UTC, benerken approved these changes

2022-06-13 05:44 UTC, closed without merging