document: `adminMetadata` displayed by default
rero/rero-ils pull request #2181
Opened 2021-07-16 07:42 UTC by zannkukai

Closes rero/rero-ils#2180.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-07-16 07:47 UTC, iGormilhit approved these changes

2021-07-16 07:52 UTC, benerken approved these changes

2021-07-19 05:51 UTC, iGormilhit requested changes
Commit message title proposition: `document: display `adminMetadata` by default`

2021-07-19 12:26 UTC, jma approved these changes

2021-07-19 12:30 UTC, merged