holdings: add delete of serials holdings
rero/rero-ils pull request #2219
Opened 2021-07-21 09:04 UTC by rerowep

* Closes #1720.

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-07-21 09:10 UTC, iGormilhit requested changes
Commit message title proposition: `holdings: allow deletion of serials holdings`

2021-07-21 09:16 UTC, iGormilhit approved these changes

2021-07-22 07:22 UTC, zannkukai approved these changes

2021-07-22 07:22 UTC, zannkukai commented on rero_ils/modules/holdings/api.py
> +            return self
cosmetic : could be merged into single line instruction

2021-07-22 07:22 UTC, zannkukai commented on rero_ils/modules/holdings/api.py
> +                        item.issue_status == ItemIssueStatus.RECEIVED:
cosmetic : cold be merged into a single `if` statement

2021-07-22 07:22 UTC, zannkukai commented on rero_ils/modules/holdings/api.py
> +                    links['items'] += 1
```python
not_deleteable_items = [item for item in self.get_items if item.reasons_not_to_delete()]
if not_deleteable_items:
    links['items'] = len(not_deleteable_items)
```

2021-07-22 09:45 UTC, jma approved these changes

2021-07-22 09:45 UTC, jma commented on rero_ils/modules/holdings/api.py
> +            if item:
Why  is it required?

2021-07-22 09:45 UTC, jma commented on tests/ui/holdings/test_holdings_patterns.py
> +    assert created_issue.delete(dbcommit=True, delindex=True)
It would be great to check that the items are deleted.

2021-07-22 11:10 UTC, iGormilhit commented
@rerowep 
When deletion is prevented because an item has an active loan attached, the reason message is not accurate.

![ksnip_20210722-130841](https://user-images.githubusercontent.com/1557213/126630179-6ffb62fa-2963-4972-a6b1-b71e006ea1be.png)

2021-07-22 14:19 UTC, BadrAly requested changes

2021-07-22 14:19 UTC, BadrAly commented on rero_ils/modules/holdings/api.py
> +        print('-----', cannot_delete)
delete `print` line

2021-07-28 11:42 UTC, Garfield-fr approved these changes

2021-08-05 12:39 UTC, JoelleDosimont commented
- When the issue is new, the page needs to be refresh to allow is to be deleted : 
![image](https://user-images.githubusercontent.com/55576980/128350572-e019622d-5141-41a8-bd64-71c7b73bb390.png)
- Some problems with the traduction when we attempt to delete a issue with loan, it mixes the French and English.
Example :
  Voulez-vous vraiment supprimer cet enregistrement ? Attached items will also be deleted.
  Vous ne pouvez pas supprimer l'enregistrement pour la raison suivante : has 1 items with loan attached
- Is there still a distinction between regular/irregular issue. The field still appear : 
![image](https://user-images.githubusercontent.com/55576980/128351055-db985827-9919-4f95-a6d0-8a494bd6fc8f.png)
- If we can delete a serial issue, I think we should remove the "deleted" issue status.

2021-08-05 14:30 UTC, BadrAly approved these changes

2021-08-12 07:12 UTC, merged