notifications: Fix wrong pick-up location name
rero/rero-ils pull request #2297
Opened 2021-08-16 10:23 UTC by rerowep

* Closes #2242

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-08-16 12:46 UTC, pronguen requested changes
The wrong issue is mentioned. Should be: #2295

2021-08-17 07:00 UTC, zannkukai approved these changes

2021-08-17 09:39 UTC, Garfield-fr approved these changes

2021-08-17 13:06 UTC, pronguen approved these changes

2021-08-18 08:04 UTC, merged