items: fix requested loans by library list
rero/rero-ils pull request #2307
Opened 2021-08-17 12:28 UTC by zannkukai

Closes rero/rero-ils#2296.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-08-18 07:18 UTC, rerowep requested changes

2021-08-18 07:18 UTC, rerowep commented on rero_ils/modules/loans/api.py
> +            if pid not in libraries:
See above (`libraries`)

2021-08-18 07:18 UTC, rerowep commented on rero_ils/modules/loans/api.py
> +            if pid not in holdings:
See above (`holdings`)

2021-08-18 07:18 UTC, rerowep commented on rero_ils/modules/loans/api.py
> +            if pid not in items:
See above (`items`)

2021-08-18 07:18 UTC, rerowep commented on rero_ils/modules/loans/api.py
> +            if pid not in item_types:
See above (`item_types`)

2021-08-18 14:29 UTC, zannkukai commented on rero_ils/modules/items/views/api_views.py
> -            raise(error)
@rerowep
I'm not agree. What's you propose is to build a new `NotFound` exception based on another `NotFound` exception.
Seems the same than write `raise NotFound(NotFound('my exception message'))`.

the python `raise` statement needs an exception as argument. In this case, the `error` variable is already a `NotFound(Exception)` exception. https://stackoverflow.com/questions/18188563/how-to-re-raise-an-exception-in-nested-try-except-blocks?answertab=votes#tab-top

2021-08-24 12:19 UTC, rerowep approved these changes

2021-09-01 12:40 UTC, BadrAly approved these changes

2021-09-09 10:25 UTC, merged