documents & holdings: remove default values on optional fields
rero/rero-ils pull request #2316
Opened 2021-08-19 06:52 UTC by Garfield-fr

* Closes #2080.

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-08-19 07:19 UTC, pronguen requested changes
One correction is missing: field `scale.type` (in `/rero_ils/modules/documents/jsonschemas/documents/document_scale_cartographic-v0.0.1.json`)

2021-08-19 07:19 UTC, pronguen commented on rero_ils/modules/documents/jsonschemas/documents/document_contribution_organisation-v0.0.1.json
> -      "default": false,
Currently, this field is present in all contribution of type "corporate body". The easiest way is to let the default value and make the field required.
If we removing the default value, we need to do mass corrections.

2021-08-19 07:41 UTC, pronguen approved these changes

2021-08-19 12:33 UTC, rerowep approved these changes

2021-08-20 08:01 UTC, benerken approved these changes

2021-09-21 09:47 UTC, iGormilhit requested changes
Commit message title proposition: `documents & holdings` → `editor`.

2021-09-22 04:58 UTC, iGormilhit approved these changes

2021-09-22 09:24 UTC, merged