documents: documents with item cli
rero/rero-ils pull request #2371
Opened 2021-09-07 17:46 UTC by rerowep

* Adds a cli for creation of documents with assoziated items.

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-09-09 06:28 UTC, zannkukai approved these changes

2021-09-21 08:27 UTC, iGormilhit requested changes
Commit message proposition:

```
documents: create documents with item CLI

* Extends item CLI for validating and creating documents with linked
  items.
```

2021-09-21 08:27 UTC, iGormilhit commented on rero_ils/modules/cli.py
> +    """Validates REROILS records with items.
```suggestion
    """Validate RERO ILS records with items.
```

2021-09-21 08:27 UTC, iGormilhit commented on rero_ils/modules/cli.py
> +        """Adds organisation, library and document to item for validation."""
```suggestion
        """Add organisation, library and document to item for validation."""
```

2021-09-21 08:27 UTC, iGormilhit commented on rero_ils/modules/cli.py
> +    :param lazy: lazy reads file
```suggestion
    :param lazy: lazy read file
```

2021-09-22 12:11 UTC, iGormilhit approved these changes

2021-09-22 13:38 UTC, benerken approved these changes

2021-09-22 13:50 UTC, BadrAly approved these changes

2021-09-23 06:59 UTC, merged