templates: $ref from data field must not be resolve
rero/rero-ils pull request #2386
Opened 2021-09-15 10:11 UTC by zannkukai

the `$ref` from the template data doesn't need to be resolved when the
record is indexed into ES. This should be cause indexing errors if the
related resource doesn't exists anymore and we will not consider this
spacial case.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>
Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-09-21 07:09 UTC, iGormilhit requested changes
Commit message proposition:

```
templates: prevent resolving $ref from data field

The `$ref` of the template data doesn't need to be resolved when the
record is indexed by ES, as it causes indexing errors when the related
resource doesn't exist anymore.
```

2021-09-23 05:29 UTC, iGormilhit approved these changes

2021-09-23 19:00 UTC, lauren-d approved these changes

2021-09-23 19:04 UTC, lauren-d commented
be careful, tests failed

2021-09-28 12:09 UTC, rerowep approved these changes

2021-09-28 12:10 UTC, merged