documents: delete main part of
rero/rero-ils pull request #2389
Opened 2021-09-15 19:22 UTC by rerowep

* Adds to the documents `reasons_not_to_delete` function the part of documents count.

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-09-16 06:25 UTC, zannkukai approved these changes

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/budgets/api.py
> +    def get_number_of_acq_accounts(self, get_pids=False):
the method name suggests that we get the number of linked acq_account. Either change the signature, either don't play with `get_pids`

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/budgets/api.py
> +        acq_accounts = self.get_number_of_acq_accounts(get_pids=get_pids)
Depending of first comment, adapt method call here

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/circ_policies/api.py
>          return links
Could you please place a `TODO` comment here to remember to have a better method implementation.

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/acq_accounts/api.py
> +    def get_number_of_acq_order_lines(self, get_pids=False):
please update method name or method signature.

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/acq_order_lines/api.py
> +    def get_number_of_acq_order_lines(self, get_pids=False):
same remarks

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/acq_orders/api.py
> +    def get_number_of_acq_order_lines(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/documents/api.py
> +    def get_number_of_items(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/documents/api.py
> +    def get_number_of_holdings(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/documents/api.py
> +    def get_number_of_loans(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/documents/api.py
> +    def get_number_of_acquisition_order_lines(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/documents/api.py
> +    def get_number_of_documents(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/holdings/api.py
> +    def get_number_of_items(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/item_types/api.py
> +    def get_number_of_items(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/items/api/circulation.py
> +    def get_number_of_loans(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/libraries/api.py
> +    def get_number_of_librarians(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/locations/api.py
> +    def get_number_of_items(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/locations/api.py
> +    def get_number_of_loans(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/organisations/api.py
> +    def get_number_of_libraries(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/patron_transactions/api.py
> +    def get_number_of_patron_transaction_events(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/patron_types/api.py
> +    def get_number_of_circ_policies(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/patron_types/api.py
> +    def get_number_of_patrons(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/patrons/api.py
> +    def get_number_of_loans(self, get_pids=False):
same

2021-09-20 08:44 UTC, zannkukai commented on rero_ils/modules/vendors/api.py
> +    def count_links_to_me(self, search_class, get_pids=False):
same

2021-09-21 06:25 UTC, iGormilhit requested changes
@rerowep I have issue to understand the commit message. We should talk about it. :slightly_smiling_face:

2021-09-21 10:11 UTC, iGormilhit requested changes
Commit message proposition:

```
documents: prevent referenced document deletion

* Verifies if a document is linked to another document before deleting
  it.
* Adds to the documents `reasons_not_to_delete` function a section with
  the documents count.
* Adds `get_pids` to all `get_links_to_me` functions to get all attached
  PIDs and counts.
```

2021-09-22 12:17 UTC, iGormilhit approved these changes

2021-09-22 13:39 UTC, benerken approved these changes

2021-09-22 13:56 UTC, BadrAly approved these changes

2021-09-22 17:32 UTC, lauren-d approved these changes

2021-09-22 17:35 UTC, lauren-d commented
be careful github actions failed

2021-09-23 20:19 UTC, merged