operation log: untrack some changes.
rero/rero-ils pull request #2395
Opened 2021-09-21 11:34 UTC by zannkukai

* Some changes should not be track by an operation log. If a circulation
  operation is done, this will change the related item status. This
  change should not be generate an operation log.
* Use the Invenio extensions to manage operation logs creation.
* Closes rero/rero-ils#1779.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-09-22 14:21 UTC, iGormilhit requested changes
Commit message proposition:

```
operation logs: untrack some changes

* Some changes should not be tracked by an operation log (!= an
  operation log for loan history). If a circulation operation is done,
  this will change the related item status, but should not generate an
  operation log as it will be shown in the operation history on resource
  such as item or document. Furthermore, the circulation operation are
  already tracked.
* Use the Invenio extensions to manage operation log creation.
* Closes rero/rero-ils#1779.
```

2021-09-24 05:33 UTC, iGormilhit approved these changes

2021-09-27 06:41 UTC, jma commented
Nice job!

2021-09-27 08:14 UTC, jma approved these changes

2021-09-28 06:46 UTC, rerowep reviewed
It would be nice to have an api end or cli function to display the operation logs ordered by date for a given type and pid.

2021-09-28 12:04 UTC, merged