operation logs: fix query if the user is both patron and librarian role
rero/rero-ils pull request #2536
Opened 2021-11-17 11:51 UTC by Garfield-fr

* Closes #2530.
* Closes #2531.

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-11-17 12:09 UTC, zannkukai approved these changes

2021-11-18 06:58 UTC, BadrAly approved these changes

2021-11-18 09:02 UTC, benerken approved these changes

2021-11-22 09:38 UTC, jma approved these changes

2021-11-22 09:39 UTC, jma requested changes
Needs to write some tests.

2021-12-06 06:33 UTC, jma approved these changes

2021-12-06 06:46 UTC, merged