PatronTransaction: fix event creation
rero/rero-ils pull request #2582
Opened 2021-12-02 17:43 UTC by zannkukai

It was unable to create a `PatronTransactionEvent` without amount.
However, it must be allowed for some event (like a dispute).

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-12-03 14:42 UTC, benerken approved these changes

2021-12-06 12:56 UTC, jma requested changes

2021-12-06 12:56 UTC, jma commented on rero_ils/modules/patron_transaction_events/api.py
> +            pass
Do you want to put a return here?

2021-12-06 14:42 UTC, vgranata approved these changes

2021-12-06 14:48 UTC, lauren-d approved these changes

2021-12-07 06:51 UTC, BadrAly approved these changes

2021-12-07 09:01 UTC, jma approved these changes

2021-12-07 09:04 UTC, merged