loans: dumping related circulation policy
rero/rero-ils pull request #2589
Opened 2021-12-09 08:30 UTC by zannkukai

Creates an API endpoint to allow dumping the circulation
policies informations related to a loan.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2021-12-09 10:10 UTC, BadrAly requested changes
I should also note that this `circulation policy` is not, all the time, the policy used for the `loan`. 
If after a `checkout`, the item has changed its `itty`, `temp_itty` or `loc` then the `api` will return a `new` circ policy which is not really the one used for the `loan`. same applies if `patron` changes its `ptty`.
so this `api` is most of the time correct except the two cases above.

future enhancement: would be nice to have the used `circ_policy` at the time of the `checkout` inside the `loan` object.

2021-12-09 10:10 UTC, BadrAly commented on rero_ils/modules/loans/api_views.py
> +def dump_loan_circulation_policies(loan_pid):
I imagine we can only have one policy for each loan: `dump_loan_circulation_policies` -> `dump_loan_circulation_policy`

2021-12-09 10:10 UTC, BadrAly commented on rero_ils/modules/circ_policies/api.py
> +    _schema = 'circ_policies/circ_policy-v0.0.1.json'
do we need this? specially it is used only by the `tests`
it is already available by 
`current_app.config.get('RECORDS_JSON_SCHEMA')[provider.pid_type]`

2021-12-09 13:15 UTC, BadrAly approved these changes

2021-12-16 09:14 UTC, benerken approved these changes

2021-12-20 08:19 UTC, merged