document: add `teaching material` document type
rero/rero-ils pull request #2668
Opened 2022-01-28 09:20 UTC by zannkukai

Closes rero/rero-ils#2666.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2022-01-28 12:40 UTC, benerken approved these changes

2022-01-28 14:32 UTC, pronguen approved these changes

2022-01-31 08:37 UTC, rerowep requested changes
There should be an image `icon_docmaintype_teaching_material.svg` in `rerp_ils/documents/static/images.

2022-01-31 11:28 UTC, JoelleDosimont approved these changes

2022-02-01 11:16 UTC, rerowep approved these changes

2022-02-04 08:57 UTC, merged