modules: add logging to create
rero/rero-ils pull request #2709
Opened 2022-02-17 16:11 UTC by rerowep

* Catches record creates errors and logs them

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2022-02-17 17:37 UTC, lauren-d requested changes

2022-02-17 17:37 UTC, lauren-d commented on rero_ils/modules/api.py
> +            print('------>', persistent_identifier)
useless ?

2022-02-21 22:58 UTC, lauren-d approved these changes

2022-02-22 07:54 UTC, jma approved these changes

2022-02-22 08:55 UTC, zannkukai approved these changes

2022-02-22 12:25 UTC, merged