Add call numbers in notification request for provisional items, filter serial items by issue status received
rero/rero-ils pull request #2749
Opened 2022-03-07 16:22 UTC by vgranata

## Why are you opening this PR?
Solves issue #2494 

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#822

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2022-03-08 13:37 UTC, Garfield-fr approved these changes

2022-03-08 13:57 UTC, BadrAly requested changes

2022-03-08 13:57 UTC, BadrAly commented on rero_ils/modules/items/api/record.py
> +        if self.get('type') == 'provisional' and not self.get('call_number'):
There is a case when the `provisional` item has a `second_call_number`, in this case you will not display the item second call number at all.

2022-03-10 11:06 UTC, BadrAly approved these changes

2022-03-10 11:13 UTC, merged