circulation: cancel intransit request with loans
rero/rero-ils pull request #2756
Opened 2022-03-10 11:25 UTC by BadrAly

Case when an item has an in_transit_for_pickup loan with other
pending loans. If the in_transit_for_pickup is cancelled, the
system will validate the first pending loan at the pickup
location of the cancelled loan. This will ensure that the
loan to validate will receive the correct state according
to the validation logic.

* Closes #2454

Co-Authored-by: Aly Badr <aly.badr@rero.ch>
Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Cypress tests successful?

2022-03-10 12:44 UTC, lauren-d approved these changes

2022-03-10 13:02 UTC, zannkukai approved these changes

2022-03-14 06:04 UTC, Garfield-fr approved these changes

2022-03-14 08:55 UTC, zannkukai requested changes
It appears that when a request is validated with 'validate_first_pending' the request `transaction_date` isn't updated. It's important to do that because the loan `request_expiration_date` is calculated on this date.

* If a REQUEST is recored à J+0 and the related cipo allow request for 7 days.
* This request is automatically validate at J+5 because the previous loan was "check-in"
* The `request_expiration_date` is calculated at J+7 instead of J+12 (12 = J+5 + 7 days).

@zannkukai as discussed, this will be put in a separate PR

2022-03-15 08:08 UTC, zannkukai approved these changes

2022-03-17 10:41 UTC, pronguen commented
- [ ] After the cancel, the 2nd request stays with `state:PENDING` (in the loan). This presents the problem that the request appears in the requests to validate, but the item is actually still in transit.
    - Expected behaviour: the 2nd request is updated to the state `IN_TRANSIT_FOR_PICKUP`

2022-03-17 15:38 UTC, PascalRepond approved these changes

2022-03-22 12:37 UTC, merged