items: add new fiels to inventory list
rero/rero-ils pull request #2960
Opened 2022-06-14 12:45 UTC by BadrAly

Adds fields from item and document resources to the inventory list.

* Fixes #2704

Co-Authored-by: Aly Badr <aly.badr@rero.ch>

2022-06-14 15:19 UTC, BadrAly commented on rero_ils/modules/items/serializers/collector.py
> +        agg = A('terms', field='item_pid.value', size=cls.chunk_size)
I'm re-writing this part, will get in touch with Laurent...

2022-06-21 06:15 UTC, BadrAly commented on rero_ils/modules/items/serializers/csv.py
> +                csv_data['item_renewals_count'] = renewals.get(hit.pid, 0)
@lauren-d: I am adding the missing fields...

2022-06-21 12:01 UTC, rerowep requested changes

2022-06-21 12:59 UTC, lauren-d commented on rero_ils/modules/items/serializers/collector.py
> +            .sort({'_created': {"order": "desc"}})\
probably not needed with execute(). must be tested.

2022-06-21 13:31 UTC, zannkukai reviewed
`get_loans_by_item_pids` is comming

2022-06-21 13:31 UTC, zannkukai commented on rero_ils/modules/items/serializers/collector.py
> +            .filter('term', loan__trigger=ItemCirculationAction.CHECKOUT)\
Mmmm...It seems that `loan.trigger` isn't mapped into ES. It should be no ?
If it's not mapped into ES, it should be analyze as "text" with a raw (keyword) children attribute (@jma : is it correct ?)
So either add this field into ES_mapping (... and create an alembic script to reindex all alive loans), either use `loan__trigger__raw`. (I vote for the first solution !)

2022-06-21 13:31 UTC, zannkukai commented on rero_ils/modules/items/serializers/collector.py
> +            .source(['loan.item.pid'])
you can add an `.extra(rows=0)` if you didn't need to check result hits.

2022-06-21 16:26 UTC, lauren-d commented on rero_ils/modules/items/serializers/collector.py
> +    def get_loans_by_item_pids(cls, item_pids=None):
could you put more comments in this method?

2022-06-27 08:10 UTC, closed without merging