update flask-wiki to 0.2.1
rero/rero-ils pull request #3002
Opened 2022-07-12 10:13 UTC by PascalRepond

Co-Authored-by: Pascal Repond <pascal.repond@rero.ch>

2022-07-25 06:55 UTC, jma requested changes
You have update all dependencies. Probably you did not change the flask-wiki using the `poetry` command.

2022-07-25 12:03 UTC, rerowep approved these changes

2022-07-25 12:09 UTC, ManaDeweerdt approved these changes

2022-07-26 06:37 UTC, jma approved these changes

2022-07-28 08:44 UTC, merged