chore: update footer info
rero/rero-ils pull request #3017
Opened 2022-07-26 06:34 UTC by PascalRepond

* Point ILS link to current release page
* RERO becomes RERO+
* Delete link to Invenio

Co-Authored-by: Pascal Repond <pascal.repond@rero.ch>

2022-07-26 06:36 UTC, jma requested changes

2022-07-26 06:36 UTC, jma commented on rero_ils/theme/templates/rero_ils/footer.html
> +      <a href="https://www.rero.ch" target="_blank">RERO+</a>
We still need to mention Invenio.

2022-07-26 06:56 UTC, Garfield-fr commented
Proposal: a simpler footer by removing the mention invenio

2022-08-02 06:46 UTC, jma approved these changes

2022-08-08 09:43 UTC, merged