documentation: update contributing guide
rero/rero-ils pull request #3024
Opened 2022-07-28 10:03 UTC by PascalRepond

Co-Authored-by: Pascal Repond <pascal.repond@rero.ch>

2022-08-02 06:37 UTC, rerowep approved these changes

2022-08-02 07:15 UTC, jma requested changes

2022-08-02 07:15 UTC, jma commented on CONTRIBUTING.rst
> +1. The pull request should include tests and must not decrease test coverage.
`must` -> `should`. Satisfying this condition is sometime not possible.

2022-08-02 07:15 UTC, jma commented on CONTRIBUTING.rst
> +2. If the pull request adds functionality, the docs should be updated. Put
I do not understand this point sorry.

2022-08-02 07:15 UTC, jma commented on CONTRIBUTING.rst
> +1. `Separate subject from body with a blank line
Please put a `.` after each item in the list.

2022-08-02 07:15 UTC, jma commented on CONTRIBUTING.rst
> +    * If your commit closes or addresses an issue, you can mention
We can also document how to refer to an issue of an other project.

2022-08-02 07:15 UTC, jma commented on CONTRIBUTING.rst
> +    * Explain the problem that this commit is solving. Focus on why you
We can also to explain how to specify a data migration procedure.

2022-08-09 06:18 UTC, BadrAly approved these changes

2022-08-10 06:49 UTC, jma approved these changes

2022-08-10 07:02 UTC, merged