tests: fix tests for the new pydocstyle version
rero/rero-ils pull request #3028
Opened 2022-08-03 08:36 UTC by jma

The new version of pydocstyle is more stric and retrun an error when
the `del` statement is used as a function.

Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

2022-08-03 13:13 UTC, Garfield-fr approved these changes

2022-08-04 07:45 UTC, zannkukai approved these changes

2022-08-04 07:54 UTC, rerowep approved these changes

2022-08-06 07:00 UTC, lauren-d approved these changes

2022-08-08 05:28 UTC, PascalRepond requested changes
Please correct typos in commit message.

2022-08-08 06:27 UTC, PascalRepond requested changes
commit message: "pydocstyle is more stric and retrun" ->"pydocstyle is more strict and returns"

2022-08-08 07:52 UTC, PascalRepond approved these changes

2022-08-08 09:40 UTC, merged