notification: enrich availability context
rero/rero-ils pull request #3146
Opened 2022-10-25 14:09 UTC by lauren-d

* Adds item's informations in context for availability notification.
* Closes rero#2693.

Co-Authored-by: Lauren-D <laurent.dubois@itld-solutions.be>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

2022-10-26 07:32 UTC, PascalRepond requested changes
To close the linked issue, the notification templates should also be modified to use this data.

2022-10-26 07:48 UTC, zannkukai approved these changes

2022-10-26 08:20 UTC, lauren-d commented on rero_ils/modules/notifications/subclasses/availability.py
> +from ...items.dumpers import ItemNotificationDumper
argff, it was an automatic import...

2022-10-26 08:44 UTC, PascalRepond approved these changes

2022-10-26 12:49 UTC, Garfield-fr approved these changes

2022-11-02 07:20 UTC, jma approved these changes

2022-12-06 08:41 UTC, merged