circulation: better logs for no circulation action
rero/rero-ils pull request #3230
Opened 2023-01-30 13:18 UTC by rerowep

* Adds information what kind of "no circulation action" was happened.

2023-01-30 16:08 UTC, zannkukai approved these changes

2023-02-06 08:13 UTC, jma requested changes

2023-02-06 08:13 UTC, jma commented on rero_ils/modules/documents/extensions.py
> +    def post_create(self, record):
Theses changes are already integrated: https://github.com/rero/rero-ils/commit/23d7575329e1c3ed25deb4a636a2f335d98ec50a

2023-02-08 10:33 UTC, jma approved these changes
Can you check the messages for translation with Pascal?

2023-02-08 10:33 UTC, jma commented on tests/api/circulation/test_actions_views_checkin.py
> +        'error: No circulation action performed: ON_SHELF'
No translation?

2023-02-09 11:26 UTC, PascalRepond approved these changes

2023-02-09 12:43 UTC, merged