utils: timestamps
rero/rero-ils pull request #3248
Opened 2023-02-07 15:32 UTC by rerowep

* Adds `name` to timestamps for better json paring in monitoring software.
* Saves also 0 values for `notification-creation` timestamp.

2023-02-08 10:13 UTC, zannkukai requested changes

2023-02-08 10:13 UTC, zannkukai commented on rero_ils/modules/notifications/tasks.py
>      counters = {k: v for k, v in notification_counter.items() if v > 0}
You tried to use `**counters` before it is initialized.
Both line should be switched

2023-02-14 08:16 UTC, zannkukai approved these changes

2023-02-15 10:24 UTC, jma approved these changes
Do we need to do a migration?

2023-02-16 16:46 UTC, merged