alembic: scripts for data migration
rero/rero-ils pull request #3251
Opened 2023-02-08 14:20 UTC by zannkukai

* Adds a script to reindex documents with invalid EAN identifier.
* Adds a script to reindex serial issue item due to complete ES record with required `sort_date` field.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

2023-02-14 13:20 UTC, lauren-d requested changes

2023-02-14 13:20 UTC, lauren-d commented on rero_ils/alembic/8145a7cdef99_reindex_items_with_invalid_ean.py
> +indexing_chunck_size = 100
The chunk size should be set to 1000

2023-02-15 10:28 UTC, jma approved these changes

2023-02-15 10:28 UTC, jma commented on rero_ils/alembic/8145a7cdef99_reindex_items_with_invalid_ean.py
> +def downgrade():
Can we remove this?

2023-02-15 10:28 UTC, jma commented on rero_ils/alembic/8145a7cdef99_reindex_items_with_invalid_ean.py
> +    query = DocumentsSearch().filter(
Difficult to say if we need to do it using invenio or if this can be performed by elasticsearch....

2023-02-15 10:28 UTC, jma commented on rero_ils/alembic/b77bbbb2760c_adding_sorted_date_es_field_to_serial_.py
> +    query = ItemsSearch().filter('term', type='issue').source(False)
Same as previous.

2023-03-06 09:49 UTC, lauren-d approved these changes

2023-03-06 11:44 UTC, merged