tests: Prevent MEF access
rero/rero-ils pull request #3263
Opened 2023-02-28 15:45 UTC by rerowep

2023-03-01 13:54 UTC, Garfield-fr approved these changes

2023-03-02 06:35 UTC, jma requested changes
Please change you commit message to respect https://github.com/rero/developer-resources/blob/master/git-github/git.md#git-commit-guidelines.

2023-03-02 06:53 UTC, zannkukai approved these changes
Change will be OK, Is it to avoid unit test problem ? Mock ?

2023-03-02 07:25 UTC, jma approved these changes

2023-03-02 09:48 UTC, merged