operation logs: add the notifications sent
rero/rero-ils pull request #3286
Opened 2023-03-22 15:32 UTC by Garfield-fr

* Closes https://github.com/rero/rero-ils/issues/2639.

2023-03-28 12:26 UTC, zannkukai requested changes

2023-03-28 12:26 UTC, zannkukai commented on rero_ils/modules/operation_logs/api.py
> +        """."""
missing docstring ;-)

2023-04-03 09:23 UTC, lauren-d approved these changes

2023-04-04 05:47 UTC, rerowep commented on rero_ils/modules/operation_logs/api.py
> +        query = self.filter('term', notification__pid=notif_pid).source()
`source()` could be deleted.

2023-04-05 05:57 UTC, merged