import: fix contribution $ref creation
rero/rero-ils pull request #3313
Opened 2023-04-18 08:03 UTC by rerowep

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

2023-04-18 12:10 UTC, zannkukai approved these changes

2023-04-20 07:32 UTC, PascalRepond requested changes
- Missing unit tests.
- Still doesn't work for gnd contribs imported from SLSP : test 9783861971870 with

<html><body>
<!--StartFragment-->

100 | 1 | _ | $a Quack, Ulrich $d 1956- $0 (DE-588)115504834 $4 aut
-- | -- | -- | --


<!--EndFragment-->
</body>
</html>

2023-04-20 09:40 UTC, zannkukai commented
> * Still doesn't work for gnd contribs imported from SLSP : test 9783861971870 with
> 
> 100	1	_	$a Quack, Ulrich $d 1956- $0 (DE-588)115504834 $4 aut
 
 This is why : `match_type = match_type.replace('de-101', 'gnd')`. Is the correct pattern should be 'de-\d+' ?

2023-04-25 08:53 UTC, PascalRepond approved these changes

2023-04-25 09:02 UTC, rerowep commented
> > * Still doesn't work for gnd contribs imported from SLSP : test 9783861971870 with
> > 
> > 100	1	_	$a Quack, Ulrich $d 1956- $0 (DE-588)115504834 $4 aut
> 
> This is why : `match_type = match_type.replace('de-101', 'gnd')`. Is the correct pattern should be `de-\d+` ?

DE-101 and DE-588 are unfortunately not always the same ID's. I may need to write a function that converts DE-588 to DE-101 with a request to GND. MEF uses DE-101 as pid because this id is the same as used for OAI-PMH.

2023-04-26 09:03 UTC, PascalRepond approved these changes

2023-05-02 07:00 UTC, zannkukai approved these changes

2023-05-02 07:27 UTC, benerken approved these changes

2023-05-02 12:51 UTC, merged