entities: sync for contributions and concepts
rero/rero-ils pull request #3342
Opened 2023-05-24 08:49 UTC by rerowep

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

2023-05-24 12:50 UTC, zannkukai requested changes

2023-05-24 13:15 UTC, rerowep commented on rero_ils/modules/entities/sync.py
> +class SyncEntity(object):
Agent is unfortunately no longer the correct word and it was not be corrected beforehand.

2023-05-24 13:46 UTC, rerowep commented on rero_ils/config.py
> +RERO_ILS_ENTITY_TYPES = {
Ok I have done a cherry-pick with `release: v1.17.0`

2023-05-25 09:32 UTC, zannkukai approved these changes

2023-05-25 12:17 UTC, PascalRepond approved these changes

2023-05-25 12:17 UTC, PascalRepond commented on rero_ils/modules/entities/sync.py
> +            # iterate over all entity sources: rero, gnd, idref
Maybe for performance, if entity type is not bf:Person or bf:Organisation, you don't need to check gnd and rero, only idref? But I don't know if it's worth differentiating the behaviour.

2023-05-25 13:17 UTC, jma approved these changes
bf:Topic sync tests seems missing.

2023-05-31 09:05 UTC, merged