items: claim notification serialization
rero/rero-ils pull request #3350
Opened 2023-06-02 08:15 UTC by zannkukai

* Adds claim notification information into ES data (for facetting)
* Adds claim notification information for item `rero+json` serializer.
* Forces `communication_language` field of `Vendor` resource as required field.

2023-06-05 06:32 UTC, lauren-d approved these changes

2023-06-06 12:59 UTC, rerowep commented on rero_ils/modules/items/api/issue.py
> +            'creation_date': datetime.now(timezone.utc).isoformat(),
See above.

2023-06-06 12:59 UTC, rerowep commented on rero_ils/modules/items/listener.py
> +        if notifications := NotificationsSearch().get_claims(record.pid):
Why not:
```python
if notifications := list(NotificationsSearch().get_claims(record.pid)):
```

2023-06-07 06:10 UTC, jma requested changes

2023-06-07 06:10 UTC, jma commented on rero_ils/modules/items/listener.py
> +            dates = list(filter(None, [
I would use an `if` condition instead of a filter.

2023-06-07 06:10 UTC, jma commented on rero_ils/modules/items/serializers/json.py
> +        """Prepare a record and persistent identifier for serialization."""
Argument description is missing.

2023-06-07 06:10 UTC, jma commented on rero_ils/modules/items/serializers/json.py
> +            if notifications := NotificationsSearch().get_claims(record.pid):
Two nested `if` can be written in one condition using an `and`.

2023-06-07 06:10 UTC, jma commented on rero_ils/modules/items/serializers/json.py
> +                dates = list(filter(None, [
Same as above.

2023-06-07 06:10 UTC, jma commented on rero_ils/modules/notifications/api.py
> +        for hit in self._get_claims_query(item_pid).scan():
Great I like this approach.

2023-06-08 06:48 UTC, zannkukai commented on rero_ils/modules/acquisition/acq_orders/api.py
> +            'creation_date': datetime.now(timezone.utc).isoformat(),
It's a little tricky to explain with my english. I will try :
the `_created` is the timestamp for the index record creation, the `creation_date` is a date than developper could choose to set in the code with any value. We thought than is some specific cases (creation errors, delayed creation notifications, ...) the creation_date are not the same than index creation.

2023-06-08 06:50 UTC, zannkukai commented on rero_ils/modules/acquisition/acq_orders/views.py
> +    emails = [
ouch 🤕  ! thx for this review !

2023-06-08 07:48 UTC, zannkukai commented on rero_ils/modules/items/serializers/json.py
> +                record['issue']['claims'] = {
I tried but such a pain ; so I keep this approach

2023-06-08 11:49 UTC, merged