billing stats: process only validated ill_requests
rero/rero-ils pull request #3381
Opened 2023-06-21 07:17 UTC by PascalRepond

- Fixes ill request stats processing for billing as contracts say only validated ill requests should be counted.
- The stats collector counts all ill_requests that were changed to status:updated.
- Requests that get validated multiple times are counted multiple times and requests created with status `validated` are not counted.
- Adds no unit tests; they will be added later for the full module.
- Closes #3359.

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

2023-06-21 09:18 UTC, mmo requested changes
Only formal changes.

2023-06-21 09:18 UTC, mmo commented on rero_ils/modules/stats/api.py
> +                    self.number_of_updated_ill_request(
```suggestion
                    self.number_of_updated_ill_requests(
```

2023-06-21 09:18 UTC, mmo commented on rero_ils/modules/stats/api.py
> +    def number_of_updated_ill_request(self, library_pid, status):
```suggestion
    def number_of_updated_ill_requests(self, library_pid, status):
```

2023-06-21 09:18 UTC, mmo commented on rero_ils/modules/stats/api.py
> +        """Number of ILL requests updates during the specified timeframe.
```suggestion
        """Number of ILL requests updated during the specified timeframe.
```

2023-06-22 11:44 UTC, zannkukai approved these changes

2023-06-27 11:51 UTC, jma approved these changes

2023-06-30 07:17 UTC, merged