documents: optimize availability
rero/rero-ils pull request #3443
Opened 2023-08-28 08:58 UTC by jma

- Uses Elasticsearch to compute the documents, items and holdings availability.
- Search only one organisation when an organisation is retrived using a view code.

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## Dependencies

My PR depends on the following `rero-ils-ui`'s PR(s):

* rero/rero-ils-ui#<xx>

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

2023-08-29 15:07 UTC, rerowep requested changes

2023-08-29 15:07 UTC, rerowep commented on rero_ils/modules/items/api/circulation.py
> +        if not bool(items_query.filter(Q('term', pid=self.pid)).count()):
Why we need `Q()` in this filter?
Could we write:
```python
if items_query.filter('term', pid=self.pid).count() == 0:
    return False
```

2023-08-30 05:32 UTC, jma commented on rero_ils/modules/documents/jsonschemas/documents/document_agent_local-v0.0.1.json
> +{
It is a mistake, sorry.

2023-08-30 05:34 UTC, jma commented on rero_ils/modules/holdings/api.py
> +        if self.get('_masked', False):
I know but as masked is a boolean, I think it is more readable.

2023-08-30 06:09 UTC, Garfield-fr approved these changes

2023-08-30 06:09 UTC, Garfield-fr commented on rero_ils/modules/documents/api.py
> +        filters = Q('term', document__pid=pid)\
Remove `\`

2023-08-30 06:09 UTC, Garfield-fr commented on rero_ils/modules/loans/api.py
> +        """."""
Missing docstring

2023-08-30 07:45 UTC, rerowep approved these changes

2023-08-30 10:09 UTC, merged

2023-08-30 11:17 UTC, zannkukai approved these changes

2023-08-30 11:17 UTC, zannkukai commented on rero_ils/modules/documents/api.py
> +        if not available_item_pids:
cosmetic : could be 
```python
if not (available_items_pids := cls.get_available_item_pids(pid, org_pid)):
    ...
```
But maybe less readable... Myself, i'm not sure

2023-08-30 11:17 UTC, zannkukai commented on rero_ils/modules/holdings/api.py
> +        loan_query = loan_query.filter(Q('terms', item_pid__value=item_pids))
Why not using same notation than everywhere else ? `filters = Q('terms, ...)`

2023-08-30 11:17 UTC, zannkukai commented on rero_ils/modules/items/api/api.py
> +                'terms', temporary_item_type__pid=not_available_item_types)
cosmetic : could be simplify

```python
has_items_filters =
    Q('terms', item_type__pid=not_available_item_types)
    & ~Q('exists', field='temporary_item_type')
    | Q('terms', temporary_item_type__pid=not_available_item_types)
```