Maj stat tasks
rero/rero-ils pull request #3524
Opened 2023-11-14 10:03 UTC by jma

2023-11-14 18:20 UTC, lauren-d approved these changes

2023-11-15 10:15 UTC, zannkukai approved these changes
This PR contains 2 commit, I only review the 'periodic task' commit

2023-11-15 10:15 UTC, zannkukai commented on rero_ils/modules/stats/api/report.py
> +from ..api.api import Stat
`..api.api`😅 This is a great mental gymnastic 🤯

2023-11-15 15:59 UTC, rerowep requested changes

2023-11-15 15:59 UTC, rerowep commented on rero_ils/config.py
> +        'schedule': crontab(minute=00, hour=1, day_of_month='1'),  # First day of the month at 01:30 UTC,
Is it working with `00`?

2023-11-15 15:59 UTC, rerowep commented on rero_ils/modules/stats/cli.py
> +@report.command('collect-all')
Could be written `@report.command()`

2023-11-15 15:59 UTC, rerowep commented on rero_ils/modules/stats/cli.py
> +        click.secho(f'Generated {len(res)} reports.')
Use `click.echo`. `click.secho` is used if color is needed.

2023-11-15 15:59 UTC, rerowep commented on rero_ils/modules/stats/cli.py
> +        collect_stats_reports.delay(frequency)
Maybe print the task id like this:
```python
res =collect_stats_reports.delay(frequency)
click.secho(f'Generated reports delayed: {res}')
```

2023-11-15 15:59 UTC, rerowep commented on rero_ils/modules/stats/tasks.py
> +    """Collect and store the montly statistics for librarian."""
Maybe test if `frequency` is `month` or `year`?

2023-11-16 09:36 UTC, rerowep approved these changes

2023-11-16 10:27 UTC, merged