acquisitions: allow reception after order was sent
rero/rero-ils pull request #3545
Opened 2023-11-30 08:44 UTC by PascalRepond

* Closes #3414.

2023-12-06 07:27 UTC, jma approved these changes

2023-12-06 07:27 UTC, jma requested changes
Please add some tests if it is possible.

2023-12-06 09:02 UTC, zannkukai approved these changes

2023-12-12 07:49 UTC, PascalRepond commented
> Please add some tests if it is possible.

I will need some help for this...

2023-12-20 08:57 UTC, PascalRepond commented
Closing as the problem seems different...

2023-12-20 08:57 UTC, closed without merging