in progress
rero/rero-ils pull request #3597
Opened 2024-02-06 09:40 UTC by jma

Signed-off-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

2024-02-20 11:56 UTC, PascalRepond commented
## Tests

- [ ] Add in the commit message "Closes https://github.com/rero/rero-ils/issues/2971"
- [ ] "full-text" toggle unclear because it is under "Show only:". Can it be a button like in SONAR to be better differentiated?

2024-02-22 12:56 UTC, rerowep requested changes

2024-02-26 07:33 UTC, jma commented on rero_ils/modules/receivers.py
> +                if tmp_f in existing_fields:
I cannot use a set as I have to deal with two different lists: fields and existing_fields

2024-02-26 08:58 UTC, PascalRepond approved these changes

2024-02-26 09:25 UTC, rerowep approved these changes

2024-02-26 09:40 UTC, Garfield-fr approved these changes

2024-02-28 08:07 UTC, lauren-d approved these changes

2024-02-28 08:07 UTC, lauren-d commented on rero_ils/query.py
> +            filters |= Q('exists', field='files')
If I understand, only document with files are displayed in organisation view right ?
What about other documents without files ?

2024-03-05 10:01 UTC, merged