facet: fix year
rero/rero-ils pull request #3605
Opened 2024-02-19 21:11 UTC by rerowep

* Fixes year facet for imports.
* Better publication year facet for documents.

2024-02-29 10:01 UTC, PascalRepond requested changes

2024-02-29 10:01 UTC, PascalRepond commented on rero_ils/config.py
> +            _('status'): and_term_filter('status'),
This should not be modified. It was just fixed, the name of the facet should be 'request_status'

2024-03-04 07:13 UTC, PascalRepond requested changes

2024-03-04 07:13 UTC, PascalRepond commented on rero_ils/config.py
> +            request_status=dict(terms=dict(field='status', size=RERO_ILS_DEFAULT_AGGREGATION_SIZE)),
Why?

2024-03-04 07:13 UTC, PascalRepond commented on rero_ils/config.py
> +            _('status'): and_term_filter('status'),
Not resolved.

2024-03-04 07:13 UTC, PascalRepond commented on rero_ils/config.py
> +            _('request_status'): and_term_filter('status'),
Why?

2024-03-04 15:38 UTC, lauren-d approved these changes

2024-04-02 08:46 UTC, merged