feat(loan): add temporary location on item
rero/rero-ils pull request #3621
Opened 2024-03-04 11:38 UTC by Garfield-fr

* Closes rero/rero-ils#3611.

2024-03-04 13:31 UTC, lauren-d approved these changes

2024-03-04 13:49 UTC, PascalRepond approved these changes

2024-03-05 09:41 UTC, jma requested changes
Tests are missing.

2024-03-05 09:41 UTC, jma commented on rero_ils/modules/loans/api.py
> +                    if 'temporary_location' in item_data:
Can you add a comment on the top of this method: it should be rewritten.

2024-03-05 11:18 UTC, jma approved these changes

2024-03-05 13:38 UTC, merged