maj files permissions
rero/rero-ils pull request #3626
Opened 2024-03-07 13:20 UTC by jma

- release: v1.21.0
- documents: add files support
- in progress

2024-03-12 07:19 UTC, lauren-d approved these changes

2024-03-12 07:19 UTC, lauren-d commented on rero_ils/modules/files/permissions.py
> +# Copyright (C) 2019-2022 RERO
`Copyright (C) 2019-2024 RERO`

2024-03-12 07:19 UTC, lauren-d commented on rero_ils/modules/files/services.py
> +# Copyright (C) 2019-2022 RERO
`Copyright (C) 2019-2024 RERO`

2024-03-12 07:19 UTC, lauren-d commented on tests/api/files/test_files_permissions.py
> +# Copyright (C) 2020 UCLouvain
`Copyright (C) 2019-2024 RERO`

2024-03-20 09:46 UTC, rerowep requested changes

2024-03-20 09:46 UTC, rerowep commented on rero_ils/modules/documents/api.py
> +            files = [hit.id for hit in file_query.scan()]
Maybe use `.source('id')`.

2024-03-20 09:46 UTC, rerowep commented on rero_ils/modules/files/cli.py
> +def create_pdf_record_files(document, metadata, flush=False, n=None):
Could you give more information for `n`. Minimum recommendation for variable/parameter length is 3! Missing in doc string `flush`, `n`.

2024-03-20 09:46 UTC, rerowep commented on rero_ils/modules/files/cli.py
>      shuffle(doc_pids)
Why we need `shuffle` and why we have `collections = ["col1", "col2", "col3"]`?
Maybe use:

```python
@click.option('-c', '--collections', multiple=True, default=["col1", "col2", "col3"])
def create_files(number, collections):
```

2024-03-21 10:38 UTC, PascalRepond commented
## PO tests

- [ ] REP: If I upload a file with an existing file name in the same bucket, the thumbnail is not displayed correctly.
![image](https://github.com/rero/rero-ils/assets/50177009/8fb7f2fc-1912-48b8-a5a6-b8d2f0fac23a)
- [ ] REP: When uploading a file, a warning should be displayed to the librarian “The files uploaded here will be publicly available. Make sure that you are legally allowed to distribute a file before adding it to a document.”
- [ ] REP: Collection list editor
    - [ ] Label should be "Digital collections"
    - [ ] The tooltip is in a different style/font than in the editors, should be the same
- [ ] REP: PRO UI: "My files" tab
    - [ ] I would rename the tab label to "Files" and adjust the title inside to "Files (my library)", if possible
    - [ ] The files in the list should be unextended by default
    - [ ] The button to extend could be clearer (an arrow on the left, like in the rest of the app instead of the "i")
    - [ ] There should be a button at the top to extend all elements at once

2024-03-25 07:25 UTC, rerowep approved these changes

2024-03-26 13:06 UTC, merged