auto renewals: add automatic_renewal task
rero/rero-ils pull request #3629
Opened 2024-03-14 10:18 UTC by PascalRepond

* Adds circ_policy field to set automatic renewals.
* Adds basic task to automatically renew loans on their due date.

2024-03-26 13:29 UTC, jma requested changes
tests are missing

2024-03-26 13:29 UTC, jma commented on rero_ils/modules/loans/api.py
> +    :return: a generator of loan pids.
This is wrong.

2024-03-26 13:29 UTC, jma commented on rero_ils/modules/loans/tasks.py
> +    """Extend all loans with an automatic renewal policy."""
Docstring is not complete.

2024-03-26 13:29 UTC, jma commented on rero_ils/modules/loans/tasks.py
> +    for loan_item in loans_to_extend:
Why do you need two loops?

2024-04-11 09:42 UTC, rerowep approved these changes

2024-05-27 13:13 UTC, closed without merging