notifications: add circulation category
rero/rero-ils pull request #3636
Opened 2024-03-25 13:34 UTC by rerowep

* Adds `Item type` and `Temporary item type` to `booking` and `request` notifications.
* Closes: #3377

2024-03-25 14:10 UTC, PascalRepond requested changes

2024-03-25 14:10 UTC, PascalRepond commented on rero_ils/modules/notifications/templates/email/booking/fre.txt
> +{%- if loan.patron.barcode %} - {{ loan.patron.barcode | join(', ') }}{%- endif %}
Patron barcode should stay below "Patron" line (18).

2024-03-25 14:10 UTC, PascalRepond commented on rero_ils/modules/items/dumpers.py
> +            'item_type': record.get('name')
Should it be record.get('item_type')['name'] ? I suspect this will return 'None'.

2024-03-26 09:50 UTC, PascalRepond approved these changes

2024-03-26 10:49 UTC, Garfield-fr approved these changes

2024-03-27 08:09 UTC, lauren-d approved these changes

2024-04-02 08:45 UTC, merged