patron_transaction_events: add item informations
rero/rero-ils pull request #3645
Opened 2024-04-08 12:19 UTC by rerowep

* Adds document and item pid to patron_transaction_events ES.
* Adds item filter to patron_transaction_events.
* Closes #3578.

2024-04-08 12:34 UTC, PascalRepond requested changes
In itself this does not close #3578, it requires another PR in the UI. Remove this line from the commit message.

2024-04-08 12:34 UTC, PascalRepond commented on rero_ils/modules/patron_transaction_events/mappings/v7/patron_transaction_events/patron_transaction_event-v0.0.1.json
> +          }
What doi you put in this `type` field?

2024-04-08 12:34 UTC, PascalRepond commented on rero_ils/modules/patron_transaction_events/mappings/v7/patron_transaction_events/patron_transaction_event-v0.0.1.json
> +            "type": "keyword"
Same question as above

2024-04-09 06:58 UTC, PascalRepond approved these changes

2024-04-09 11:38 UTC, benerken approved these changes

2024-04-09 14:25 UTC, Garfield-fr approved these changes

2024-04-10 07:50 UTC, merged