import: fix SLSP
rero/rero-ils pull request #3751
Opened 2024-09-04 20:56 UTC by rerowep

* Fixes error for SLSP imports with incorrect 008.

2024-09-05 06:04 UTC, PascalRepond requested changes

2024-09-05 06:04 UTC, PascalRepond commented on rero_ils/modules/documents/dojson/contrib/marc21tojson/slsp/model.py
> +    if len(value) >= 33:
Should be ">33" because if `len(value) == 33`, `value[33]` will be an error

2024-09-05 06:33 UTC, PascalRepond approved these changes

2024-09-10 05:53 UTC, jma approved these changes
Tests are missing.

2024-09-10 06:27 UTC, merged