general: fix robots cache timeout
rero/rero-ils pull request #3775
Opened 2024-11-11 10:44 UTC by rerowep

2024-11-11 12:19 UTC, Garfield-fr approved these changes

2024-11-11 12:55 UTC, PascalRepond approved these changes

2024-11-13 06:53 UTC, jma requested changes

2024-11-13 06:53 UTC, jma commented on rero_ils/modules/cli/utils.py
> +@cached(timeout=2 * 60 * 60, query_string=True)  # 2 hour timeout
You need to use key_prefix for non route function and meomize (need to change get_document_types_from_schema ) for class methods: https://flask-caching.readthedocs.io/en/latest/#caching-other-functions. Maybe we need to use flask-caching directely.

2024-11-18 13:41 UTC, jma approved these changes

2024-11-19 09:20 UTC, merged