fix(documents): delete orphan harvested documents
rero/rero-ils pull request #3777
Opened 2024-11-12 08:13 UTC by PascalRepond

* Closes #3776.

2024-11-12 10:29 UTC, rerowep requested changes

2024-11-12 10:29 UTC, rerowep commented on rero_ils/modules/documents/tasks.py
> +                        doc.delete(dbcommit=True, delindex=True, force=True)
Not sure `force=True` will do the trick. Force will delete the persistent identifier in DB. I think yo have to set `harvested` to `False` before deleting.

2024-11-18 12:55 UTC, jma approved these changes

2024-11-18 12:55 UTC, jma commented on rero_ils/modules/documents/tasks.py
> +                        click.secho(f"ERROR: {msg}", fg="red")
same

2024-11-20 07:41 UTC, merged