WIP documentation: fill in changes and release files
rero/rero-ils pull request #565
Opened 2019-10-16 12:32 UTC by iGormilhit

* NEW Fills in the CHANGES.rst file.
* NEW Fills in the RELEASE-NOTES.rst file.

Co-Authored-by: Igor Milhit <igor.milhit@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2019-10-17 12:37 UTC, pronguen approved these changes

2019-10-23 06:50 UTC, BadrAly requested changes

2019-10-23 06:50 UTC, BadrAly commented on RELEASE-NOTES.rst
> +|   Email: info@rero.chch
`rero.ch' instead of 'rero.chch'

2019-10-23 06:52 UTC, AoNoOokami approved these changes

2019-10-23 07:09 UTC, mmo requested changes

2019-10-23 08:39 UTC, BadrAly approved these changes

2019-10-23 12:24 UTC, merged