translation: Fix user message when an item is requested
rero/rero-ils pull request #591
Opened 2019-10-29 13:08 UTC by zannkukai

* Fix translation string "the item has been requested" with variable item_id.
* Closes #404.

Co-Authored-by: Renaud Michotte <renaud.michotte@gmail.com>

## Additional informations

- string translations done in Transifex
- "Github" typo fix into `frontpage` template ('H' should be in uppercase) 

## How to test?

- Logged as an basic user
- Ensure you choose an other language than "English" 
- Search about a document that can be requested
- Request the item.
- The flash message top/right of the screen should be displayed in the interface language

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?

2019-10-30 07:26 UTC, iGormilhit requested changes
Commit message:
- no uppercase in the commit message title
- verb at the third singular person in the commit message body (fixes)
Thanks.

2019-10-31 08:18 UTC, jma requested changes

2019-10-31 08:18 UTC, jma commented on rero_ils/translations/messages.pot
> -#: rero_ils/templates/rero_ils/frontpage.html:78
This does not come from your PR. It seems that translations are not up to date. Can you check that we do not loose translations from transifex. You have similar cases latter in this file.

2019-10-31 08:19 UTC, jma commented
You can the githup spelling correction in you commit message.

2019-10-31 09:24 UTC, jma approved these changes

2019-10-31 09:26 UTC, merged